
include_directories(serving-2.9.0)
include_directories(tensorflow-2.9.0)
include_directories(pb_out)

aux_source_directory(serving-2.9.0/tensorflow_serving/apis TF2SRC)
aux_source_directory(serving-2.9.0/tensorflow_serving/batching TF2SRC)
aux_source_directory(serving-2.9.0/tensorflow_serving/core TF2SRC)
aux_source_directory(serving-2.9.0/tensorflow_serving/model_servers TF2SRC)
aux_source_directory(serving-2.9.0/tensorflow_serving/resources TF2SRC)
aux_source_directory(serving-2.9.0/tensorflow_serving/servables/hashmap TF2SRC)
aux_source_directory(serving-2.9.0/tensorflow_serving/servables/tensorflow TF2SRC)
aux_source_directory(serving-2.9.0/tensorflow_serving/servables/tensorflow/oss TF2SRC)
aux_source_directory(serving-2.9.0/tensorflow_serving/session_bundle TF2SRC)
aux_source_directory(serving-2.9.0/tensorflow_serving/session_bundle/oss TF2SRC)
aux_source_directory(serving-2.9.0/tensorflow_serving/sources/storage_path TF2SRC)
aux_source_directory(serving-2.9.0/tensorflow_serving/util TF2SRC)

aux_source_directory(tensorflow-2.9.0/tensorflow/c TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/cc/client TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/cc/framework TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/cc/gradients TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/cc/ops TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/cc/saved_model TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/cc/tools TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/cc/training TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/compiler TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/activity_watcher TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/api_def TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/common_runtime TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/config TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/data TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/debug TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/framework TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/function TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/graph TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/grappler TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/ir TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/kernels TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/lib TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/nccl TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/ops TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/platform TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/profiler TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/protobuf TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/public TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/runtime_fallback TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/summary TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/tfrt TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/transforms TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/user_ops TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/core/util TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/dtensor TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/security TF2SRC)
aux_source_directory(tensorflow-2.9.0/tensorflow/stream_executor TF2SRC)

add_executable(tf2 ${TF2SRC})


