// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: tensorflow/python/util/protobuf/compare_test.proto
// Original file comments:
// Test messages used in compare_test.py.
#ifndef GRPC_tensorflow_2fpython_2futil_2fprotobuf_2fcompare_5ftest_2eproto__INCLUDED
#define GRPC_tensorflow_2fpython_2futil_2fprotobuf_2fcompare_5ftest_2eproto__INCLUDED

#include "tensorflow/python/util/protobuf/compare_test.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace compare_test {

}  // namespace compare_test


#endif  // GRPC_tensorflow_2fpython_2futil_2fprotobuf_2fcompare_5ftest_2eproto__INCLUDED
