// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/util/autotune_maps/conv_parameters.proto

#ifndef PROTOBUF_INCLUDED_tensorflow_2fcore_2futil_2fautotune_5fmaps_2fconv_5fparameters_2eproto
#define PROTOBUF_INCLUDED_tensorflow_2fcore_2futil_2fautotune_5fmaps_2fconv_5fparameters_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "tensorflow/core/framework/types.pb.h"
#include "tensorflow/stream_executor/dnn.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_tensorflow_2fcore_2futil_2fautotune_5fmaps_2fconv_5fparameters_2eproto 

namespace protobuf_tensorflow_2fcore_2futil_2fautotune_5fmaps_2fconv_5fparameters_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_tensorflow_2fcore_2futil_2fautotune_5fmaps_2fconv_5fparameters_2eproto
namespace tensorflow {
class ConvParametersProto;
class ConvParametersProtoDefaultTypeInternal;
extern ConvParametersProtoDefaultTypeInternal _ConvParametersProto_default_instance_;
class ConvParametersProto_Fusion;
class ConvParametersProto_FusionDefaultTypeInternal;
extern ConvParametersProto_FusionDefaultTypeInternal _ConvParametersProto_Fusion_default_instance_;
}  // namespace tensorflow
namespace google {
namespace protobuf {
template<> ::tensorflow::ConvParametersProto* Arena::CreateMaybeMessage<::tensorflow::ConvParametersProto>(Arena*);
template<> ::tensorflow::ConvParametersProto_Fusion* Arena::CreateMaybeMessage<::tensorflow::ConvParametersProto_Fusion>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace tensorflow {

// ===================================================================

class ConvParametersProto_Fusion : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.ConvParametersProto.Fusion) */ {
 public:
  ConvParametersProto_Fusion();
  virtual ~ConvParametersProto_Fusion();

  ConvParametersProto_Fusion(const ConvParametersProto_Fusion& from);

  inline ConvParametersProto_Fusion& operator=(const ConvParametersProto_Fusion& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConvParametersProto_Fusion(ConvParametersProto_Fusion&& from) noexcept
    : ConvParametersProto_Fusion() {
    *this = ::std::move(from);
  }

  inline ConvParametersProto_Fusion& operator=(ConvParametersProto_Fusion&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ConvParametersProto_Fusion& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConvParametersProto_Fusion* internal_default_instance() {
    return reinterpret_cast<const ConvParametersProto_Fusion*>(
               &_ConvParametersProto_Fusion_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ConvParametersProto_Fusion* other);
  friend void swap(ConvParametersProto_Fusion& a, ConvParametersProto_Fusion& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConvParametersProto_Fusion* New() const final {
    return CreateMaybeMessage<ConvParametersProto_Fusion>(NULL);
  }

  ConvParametersProto_Fusion* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ConvParametersProto_Fusion>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ConvParametersProto_Fusion& from);
  void MergeFrom(const ConvParametersProto_Fusion& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConvParametersProto_Fusion* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool is_contrib = 1;
  void clear_is_contrib();
  static const int kIsContribFieldNumber = 1;
  bool is_contrib() const;
  void set_is_contrib(bool value);

  // .stream_executor.dnn.ActivationMode activation_mode = 2;
  void clear_activation_mode();
  static const int kActivationModeFieldNumber = 2;
  ::stream_executor::dnn::ActivationMode activation_mode() const;
  void set_activation_mode(::stream_executor::dnn::ActivationMode value);

  // double conv_scale = 3;
  void clear_conv_scale();
  static const int kConvScaleFieldNumber = 3;
  double conv_scale() const;
  void set_conv_scale(double value);

  // double side_input_scale = 4;
  void clear_side_input_scale();
  static const int kSideInputScaleFieldNumber = 4;
  double side_input_scale() const;
  void set_side_input_scale(double value);

  // @@protoc_insertion_point(class_scope:tensorflow.ConvParametersProto.Fusion)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool is_contrib_;
  int activation_mode_;
  double conv_scale_;
  double side_input_scale_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tensorflow_2fcore_2futil_2fautotune_5fmaps_2fconv_5fparameters_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ConvParametersProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.ConvParametersProto) */ {
 public:
  ConvParametersProto();
  virtual ~ConvParametersProto();

  ConvParametersProto(const ConvParametersProto& from);

  inline ConvParametersProto& operator=(const ConvParametersProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConvParametersProto(ConvParametersProto&& from) noexcept
    : ConvParametersProto() {
    *this = ::std::move(from);
  }

  inline ConvParametersProto& operator=(ConvParametersProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ConvParametersProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConvParametersProto* internal_default_instance() {
    return reinterpret_cast<const ConvParametersProto*>(
               &_ConvParametersProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ConvParametersProto* other);
  friend void swap(ConvParametersProto& a, ConvParametersProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConvParametersProto* New() const final {
    return CreateMaybeMessage<ConvParametersProto>(NULL);
  }

  ConvParametersProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ConvParametersProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ConvParametersProto& from);
  void MergeFrom(const ConvParametersProto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConvParametersProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ConvParametersProto_Fusion Fusion;

  // accessors -------------------------------------------------------

  // repeated int64 in = 4;
  int in_size() const;
  void clear_in();
  static const int kInFieldNumber = 4;
  ::google::protobuf::int64 in(int index) const;
  void set_in(int index, ::google::protobuf::int64 value);
  void add_in(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      in() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_in();

  // repeated int64 filter = 6;
  int filter_size() const;
  void clear_filter();
  static const int kFilterFieldNumber = 6;
  ::google::protobuf::int64 filter(int index) const;
  void set_filter(int index, ::google::protobuf::int64 value);
  void add_filter(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      filter() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_filter();

  // repeated int64 dilation = 7;
  int dilation_size() const;
  void clear_dilation();
  static const int kDilationFieldNumber = 7;
  ::google::protobuf::int64 dilation(int index) const;
  void set_dilation(int index, ::google::protobuf::int64 value);
  void add_dilation(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      dilation() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_dilation();

  // repeated int64 stride = 8;
  int stride_size() const;
  void clear_stride();
  static const int kStrideFieldNumber = 8;
  ::google::protobuf::int64 stride(int index) const;
  void set_stride(int index, ::google::protobuf::int64 value);
  void add_stride(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      stride() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_stride();

  // repeated int64 padding = 9;
  int padding_size() const;
  void clear_padding();
  static const int kPaddingFieldNumber = 9;
  ::google::protobuf::int64 padding(int index) const;
  void set_padding(int index, ::google::protobuf::int64 value);
  void add_padding(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      padding() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_padding();

  // string device_identifier = 12;
  void clear_device_identifier();
  static const int kDeviceIdentifierFieldNumber = 12;
  const ::std::string& device_identifier() const;
  void set_device_identifier(const ::std::string& value);
  #if LANG_CXX11
  void set_device_identifier(::std::string&& value);
  #endif
  void set_device_identifier(const char* value);
  void set_device_identifier(const char* value, size_t size);
  ::std::string* mutable_device_identifier();
  ::std::string* release_device_identifier();
  void set_allocated_device_identifier(::std::string* device_identifier);

  // .tensorflow.ConvParametersProto.Fusion fusion = 13;
  bool has_fusion() const;
  void clear_fusion();
  static const int kFusionFieldNumber = 13;
  private:
  const ::tensorflow::ConvParametersProto_Fusion& _internal_fusion() const;
  public:
  const ::tensorflow::ConvParametersProto_Fusion& fusion() const;
  ::tensorflow::ConvParametersProto_Fusion* release_fusion();
  ::tensorflow::ConvParametersProto_Fusion* mutable_fusion();
  void set_allocated_fusion(::tensorflow::ConvParametersProto_Fusion* fusion);

  // int64 batch = 1;
  void clear_batch();
  static const int kBatchFieldNumber = 1;
  ::google::protobuf::int64 batch() const;
  void set_batch(::google::protobuf::int64 value);

  // int64 in_depths = 2;
  void clear_in_depths();
  static const int kInDepthsFieldNumber = 2;
  ::google::protobuf::int64 in_depths() const;
  void set_in_depths(::google::protobuf::int64 value);

  // int64 out_depths = 3;
  void clear_out_depths();
  static const int kOutDepthsFieldNumber = 3;
  ::google::protobuf::int64 out_depths() const;
  void set_out_depths(::google::protobuf::int64 value);

  // int32 data_format = 5;
  void clear_data_format();
  static const int kDataFormatFieldNumber = 5;
  ::google::protobuf::int32 data_format() const;
  void set_data_format(::google::protobuf::int32 value);

  // .tensorflow.DataType dtype = 10;
  void clear_dtype();
  static const int kDtypeFieldNumber = 10;
  ::tensorflow::DataType dtype() const;
  void set_dtype(::tensorflow::DataType value);

  // int32 group_count = 11;
  void clear_group_count();
  static const int kGroupCountFieldNumber = 11;
  ::google::protobuf::int32 group_count() const;
  void set_group_count(::google::protobuf::int32 value);

  // int32 version = 14;
  void clear_version();
  static const int kVersionFieldNumber = 14;
  ::google::protobuf::int32 version() const;
  void set_version(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tensorflow.ConvParametersProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > in_;
  mutable int _in_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > filter_;
  mutable int _filter_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > dilation_;
  mutable int _dilation_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > stride_;
  mutable int _stride_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > padding_;
  mutable int _padding_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr device_identifier_;
  ::tensorflow::ConvParametersProto_Fusion* fusion_;
  ::google::protobuf::int64 batch_;
  ::google::protobuf::int64 in_depths_;
  ::google::protobuf::int64 out_depths_;
  ::google::protobuf::int32 data_format_;
  int dtype_;
  ::google::protobuf::int32 group_count_;
  ::google::protobuf::int32 version_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tensorflow_2fcore_2futil_2fautotune_5fmaps_2fconv_5fparameters_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ConvParametersProto_Fusion

// bool is_contrib = 1;
inline void ConvParametersProto_Fusion::clear_is_contrib() {
  is_contrib_ = false;
}
inline bool ConvParametersProto_Fusion::is_contrib() const {
  // @@protoc_insertion_point(field_get:tensorflow.ConvParametersProto.Fusion.is_contrib)
  return is_contrib_;
}
inline void ConvParametersProto_Fusion::set_is_contrib(bool value) {
  
  is_contrib_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.ConvParametersProto.Fusion.is_contrib)
}

// .stream_executor.dnn.ActivationMode activation_mode = 2;
inline void ConvParametersProto_Fusion::clear_activation_mode() {
  activation_mode_ = 0;
}
inline ::stream_executor::dnn::ActivationMode ConvParametersProto_Fusion::activation_mode() const {
  // @@protoc_insertion_point(field_get:tensorflow.ConvParametersProto.Fusion.activation_mode)
  return static_cast< ::stream_executor::dnn::ActivationMode >(activation_mode_);
}
inline void ConvParametersProto_Fusion::set_activation_mode(::stream_executor::dnn::ActivationMode value) {
  
  activation_mode_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.ConvParametersProto.Fusion.activation_mode)
}

// double conv_scale = 3;
inline void ConvParametersProto_Fusion::clear_conv_scale() {
  conv_scale_ = 0;
}
inline double ConvParametersProto_Fusion::conv_scale() const {
  // @@protoc_insertion_point(field_get:tensorflow.ConvParametersProto.Fusion.conv_scale)
  return conv_scale_;
}
inline void ConvParametersProto_Fusion::set_conv_scale(double value) {
  
  conv_scale_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.ConvParametersProto.Fusion.conv_scale)
}

// double side_input_scale = 4;
inline void ConvParametersProto_Fusion::clear_side_input_scale() {
  side_input_scale_ = 0;
}
inline double ConvParametersProto_Fusion::side_input_scale() const {
  // @@protoc_insertion_point(field_get:tensorflow.ConvParametersProto.Fusion.side_input_scale)
  return side_input_scale_;
}
inline void ConvParametersProto_Fusion::set_side_input_scale(double value) {
  
  side_input_scale_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.ConvParametersProto.Fusion.side_input_scale)
}

// -------------------------------------------------------------------

// ConvParametersProto

// int64 batch = 1;
inline void ConvParametersProto::clear_batch() {
  batch_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 ConvParametersProto::batch() const {
  // @@protoc_insertion_point(field_get:tensorflow.ConvParametersProto.batch)
  return batch_;
}
inline void ConvParametersProto::set_batch(::google::protobuf::int64 value) {
  
  batch_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.ConvParametersProto.batch)
}

// int64 in_depths = 2;
inline void ConvParametersProto::clear_in_depths() {
  in_depths_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 ConvParametersProto::in_depths() const {
  // @@protoc_insertion_point(field_get:tensorflow.ConvParametersProto.in_depths)
  return in_depths_;
}
inline void ConvParametersProto::set_in_depths(::google::protobuf::int64 value) {
  
  in_depths_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.ConvParametersProto.in_depths)
}

// int64 out_depths = 3;
inline void ConvParametersProto::clear_out_depths() {
  out_depths_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 ConvParametersProto::out_depths() const {
  // @@protoc_insertion_point(field_get:tensorflow.ConvParametersProto.out_depths)
  return out_depths_;
}
inline void ConvParametersProto::set_out_depths(::google::protobuf::int64 value) {
  
  out_depths_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.ConvParametersProto.out_depths)
}

// repeated int64 in = 4;
inline int ConvParametersProto::in_size() const {
  return in_.size();
}
inline void ConvParametersProto::clear_in() {
  in_.Clear();
}
inline ::google::protobuf::int64 ConvParametersProto::in(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.ConvParametersProto.in)
  return in_.Get(index);
}
inline void ConvParametersProto::set_in(int index, ::google::protobuf::int64 value) {
  in_.Set(index, value);
  // @@protoc_insertion_point(field_set:tensorflow.ConvParametersProto.in)
}
inline void ConvParametersProto::add_in(::google::protobuf::int64 value) {
  in_.Add(value);
  // @@protoc_insertion_point(field_add:tensorflow.ConvParametersProto.in)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
ConvParametersProto::in() const {
  // @@protoc_insertion_point(field_list:tensorflow.ConvParametersProto.in)
  return in_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
ConvParametersProto::mutable_in() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.ConvParametersProto.in)
  return &in_;
}

// int32 data_format = 5;
inline void ConvParametersProto::clear_data_format() {
  data_format_ = 0;
}
inline ::google::protobuf::int32 ConvParametersProto::data_format() const {
  // @@protoc_insertion_point(field_get:tensorflow.ConvParametersProto.data_format)
  return data_format_;
}
inline void ConvParametersProto::set_data_format(::google::protobuf::int32 value) {
  
  data_format_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.ConvParametersProto.data_format)
}

// repeated int64 filter = 6;
inline int ConvParametersProto::filter_size() const {
  return filter_.size();
}
inline void ConvParametersProto::clear_filter() {
  filter_.Clear();
}
inline ::google::protobuf::int64 ConvParametersProto::filter(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.ConvParametersProto.filter)
  return filter_.Get(index);
}
inline void ConvParametersProto::set_filter(int index, ::google::protobuf::int64 value) {
  filter_.Set(index, value);
  // @@protoc_insertion_point(field_set:tensorflow.ConvParametersProto.filter)
}
inline void ConvParametersProto::add_filter(::google::protobuf::int64 value) {
  filter_.Add(value);
  // @@protoc_insertion_point(field_add:tensorflow.ConvParametersProto.filter)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
ConvParametersProto::filter() const {
  // @@protoc_insertion_point(field_list:tensorflow.ConvParametersProto.filter)
  return filter_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
ConvParametersProto::mutable_filter() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.ConvParametersProto.filter)
  return &filter_;
}

// repeated int64 dilation = 7;
inline int ConvParametersProto::dilation_size() const {
  return dilation_.size();
}
inline void ConvParametersProto::clear_dilation() {
  dilation_.Clear();
}
inline ::google::protobuf::int64 ConvParametersProto::dilation(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.ConvParametersProto.dilation)
  return dilation_.Get(index);
}
inline void ConvParametersProto::set_dilation(int index, ::google::protobuf::int64 value) {
  dilation_.Set(index, value);
  // @@protoc_insertion_point(field_set:tensorflow.ConvParametersProto.dilation)
}
inline void ConvParametersProto::add_dilation(::google::protobuf::int64 value) {
  dilation_.Add(value);
  // @@protoc_insertion_point(field_add:tensorflow.ConvParametersProto.dilation)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
ConvParametersProto::dilation() const {
  // @@protoc_insertion_point(field_list:tensorflow.ConvParametersProto.dilation)
  return dilation_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
ConvParametersProto::mutable_dilation() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.ConvParametersProto.dilation)
  return &dilation_;
}

// repeated int64 stride = 8;
inline int ConvParametersProto::stride_size() const {
  return stride_.size();
}
inline void ConvParametersProto::clear_stride() {
  stride_.Clear();
}
inline ::google::protobuf::int64 ConvParametersProto::stride(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.ConvParametersProto.stride)
  return stride_.Get(index);
}
inline void ConvParametersProto::set_stride(int index, ::google::protobuf::int64 value) {
  stride_.Set(index, value);
  // @@protoc_insertion_point(field_set:tensorflow.ConvParametersProto.stride)
}
inline void ConvParametersProto::add_stride(::google::protobuf::int64 value) {
  stride_.Add(value);
  // @@protoc_insertion_point(field_add:tensorflow.ConvParametersProto.stride)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
ConvParametersProto::stride() const {
  // @@protoc_insertion_point(field_list:tensorflow.ConvParametersProto.stride)
  return stride_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
ConvParametersProto::mutable_stride() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.ConvParametersProto.stride)
  return &stride_;
}

// repeated int64 padding = 9;
inline int ConvParametersProto::padding_size() const {
  return padding_.size();
}
inline void ConvParametersProto::clear_padding() {
  padding_.Clear();
}
inline ::google::protobuf::int64 ConvParametersProto::padding(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.ConvParametersProto.padding)
  return padding_.Get(index);
}
inline void ConvParametersProto::set_padding(int index, ::google::protobuf::int64 value) {
  padding_.Set(index, value);
  // @@protoc_insertion_point(field_set:tensorflow.ConvParametersProto.padding)
}
inline void ConvParametersProto::add_padding(::google::protobuf::int64 value) {
  padding_.Add(value);
  // @@protoc_insertion_point(field_add:tensorflow.ConvParametersProto.padding)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
ConvParametersProto::padding() const {
  // @@protoc_insertion_point(field_list:tensorflow.ConvParametersProto.padding)
  return padding_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
ConvParametersProto::mutable_padding() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.ConvParametersProto.padding)
  return &padding_;
}

// .tensorflow.DataType dtype = 10;
inline void ConvParametersProto::clear_dtype() {
  dtype_ = 0;
}
inline ::tensorflow::DataType ConvParametersProto::dtype() const {
  // @@protoc_insertion_point(field_get:tensorflow.ConvParametersProto.dtype)
  return static_cast< ::tensorflow::DataType >(dtype_);
}
inline void ConvParametersProto::set_dtype(::tensorflow::DataType value) {
  
  dtype_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.ConvParametersProto.dtype)
}

// int32 group_count = 11;
inline void ConvParametersProto::clear_group_count() {
  group_count_ = 0;
}
inline ::google::protobuf::int32 ConvParametersProto::group_count() const {
  // @@protoc_insertion_point(field_get:tensorflow.ConvParametersProto.group_count)
  return group_count_;
}
inline void ConvParametersProto::set_group_count(::google::protobuf::int32 value) {
  
  group_count_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.ConvParametersProto.group_count)
}

// string device_identifier = 12;
inline void ConvParametersProto::clear_device_identifier() {
  device_identifier_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConvParametersProto::device_identifier() const {
  // @@protoc_insertion_point(field_get:tensorflow.ConvParametersProto.device_identifier)
  return device_identifier_.GetNoArena();
}
inline void ConvParametersProto::set_device_identifier(const ::std::string& value) {
  
  device_identifier_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tensorflow.ConvParametersProto.device_identifier)
}
#if LANG_CXX11
inline void ConvParametersProto::set_device_identifier(::std::string&& value) {
  
  device_identifier_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tensorflow.ConvParametersProto.device_identifier)
}
#endif
inline void ConvParametersProto::set_device_identifier(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  device_identifier_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tensorflow.ConvParametersProto.device_identifier)
}
inline void ConvParametersProto::set_device_identifier(const char* value, size_t size) {
  
  device_identifier_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tensorflow.ConvParametersProto.device_identifier)
}
inline ::std::string* ConvParametersProto::mutable_device_identifier() {
  
  // @@protoc_insertion_point(field_mutable:tensorflow.ConvParametersProto.device_identifier)
  return device_identifier_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConvParametersProto::release_device_identifier() {
  // @@protoc_insertion_point(field_release:tensorflow.ConvParametersProto.device_identifier)
  
  return device_identifier_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConvParametersProto::set_allocated_device_identifier(::std::string* device_identifier) {
  if (device_identifier != NULL) {
    
  } else {
    
  }
  device_identifier_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_identifier);
  // @@protoc_insertion_point(field_set_allocated:tensorflow.ConvParametersProto.device_identifier)
}

// .tensorflow.ConvParametersProto.Fusion fusion = 13;
inline bool ConvParametersProto::has_fusion() const {
  return this != internal_default_instance() && fusion_ != NULL;
}
inline void ConvParametersProto::clear_fusion() {
  if (GetArenaNoVirtual() == NULL && fusion_ != NULL) {
    delete fusion_;
  }
  fusion_ = NULL;
}
inline const ::tensorflow::ConvParametersProto_Fusion& ConvParametersProto::_internal_fusion() const {
  return *fusion_;
}
inline const ::tensorflow::ConvParametersProto_Fusion& ConvParametersProto::fusion() const {
  const ::tensorflow::ConvParametersProto_Fusion* p = fusion_;
  // @@protoc_insertion_point(field_get:tensorflow.ConvParametersProto.fusion)
  return p != NULL ? *p : *reinterpret_cast<const ::tensorflow::ConvParametersProto_Fusion*>(
      &::tensorflow::_ConvParametersProto_Fusion_default_instance_);
}
inline ::tensorflow::ConvParametersProto_Fusion* ConvParametersProto::release_fusion() {
  // @@protoc_insertion_point(field_release:tensorflow.ConvParametersProto.fusion)
  
  ::tensorflow::ConvParametersProto_Fusion* temp = fusion_;
  fusion_ = NULL;
  return temp;
}
inline ::tensorflow::ConvParametersProto_Fusion* ConvParametersProto::mutable_fusion() {
  
  if (fusion_ == NULL) {
    auto* p = CreateMaybeMessage<::tensorflow::ConvParametersProto_Fusion>(GetArenaNoVirtual());
    fusion_ = p;
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.ConvParametersProto.fusion)
  return fusion_;
}
inline void ConvParametersProto::set_allocated_fusion(::tensorflow::ConvParametersProto_Fusion* fusion) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete fusion_;
  }
  if (fusion) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      fusion = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, fusion, submessage_arena);
    }
    
  } else {
    
  }
  fusion_ = fusion;
  // @@protoc_insertion_point(field_set_allocated:tensorflow.ConvParametersProto.fusion)
}

// int32 version = 14;
inline void ConvParametersProto::clear_version() {
  version_ = 0;
}
inline ::google::protobuf::int32 ConvParametersProto::version() const {
  // @@protoc_insertion_point(field_get:tensorflow.ConvParametersProto.version)
  return version_;
}
inline void ConvParametersProto::set_version(::google::protobuf::int32 value) {
  
  version_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.ConvParametersProto.version)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace tensorflow

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_tensorflow_2fcore_2futil_2fautotune_5fmaps_2fconv_5fparameters_2eproto
