// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/profiler/protobuf/pod_stats.proto

#include "tensorflow/core/profiler/protobuf/pod_stats.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fdiagnostics_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fdiagnostics_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Diagnostics;
}  // namespace protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fdiagnostics_2eproto
namespace protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_PodStatsRecord_StepBreakdownUsEntry_DoNotUse;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_StepBreakdownEvents;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_PodStatsRecord;
}  // namespace protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto
namespace tensorflow {
namespace profiler {
class StepBreakdownEventsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<StepBreakdownEvents>
      _instance;
} _StepBreakdownEvents_default_instance_;
class PodStatsDatabaseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PodStatsDatabase>
      _instance;
} _PodStatsDatabase_default_instance_;
class PodStatsRecord_StepBreakdownUsEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PodStatsRecord_StepBreakdownUsEntry_DoNotUse>
      _instance;
} _PodStatsRecord_StepBreakdownUsEntry_DoNotUse_default_instance_;
class PodStatsRecordDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PodStatsRecord>
      _instance;
} _PodStatsRecord_default_instance_;
}  // namespace profiler
}  // namespace tensorflow
namespace protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto {
static void InitDefaultsStepBreakdownEvents() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tensorflow::profiler::_StepBreakdownEvents_default_instance_;
    new (ptr) ::tensorflow::profiler::StepBreakdownEvents();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tensorflow::profiler::StepBreakdownEvents::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_StepBreakdownEvents =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsStepBreakdownEvents}, {}};

static void InitDefaultsPodStatsDatabase() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tensorflow::profiler::_PodStatsDatabase_default_instance_;
    new (ptr) ::tensorflow::profiler::PodStatsDatabase();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tensorflow::profiler::PodStatsDatabase::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<3> scc_info_PodStatsDatabase =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 3, InitDefaultsPodStatsDatabase}, {
      &protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::scc_info_PodStatsRecord.base,
      &protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fdiagnostics_2eproto::scc_info_Diagnostics.base,
      &protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::scc_info_StepBreakdownEvents.base,}};

static void InitDefaultsPodStatsRecord_StepBreakdownUsEntry_DoNotUse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tensorflow::profiler::_PodStatsRecord_StepBreakdownUsEntry_DoNotUse_default_instance_;
    new (ptr) ::tensorflow::profiler::PodStatsRecord_StepBreakdownUsEntry_DoNotUse();
  }
  ::tensorflow::profiler::PodStatsRecord_StepBreakdownUsEntry_DoNotUse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_PodStatsRecord_StepBreakdownUsEntry_DoNotUse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPodStatsRecord_StepBreakdownUsEntry_DoNotUse}, {}};

static void InitDefaultsPodStatsRecord() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::tensorflow::profiler::_PodStatsRecord_default_instance_;
    new (ptr) ::tensorflow::profiler::PodStatsRecord();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tensorflow::profiler::PodStatsRecord::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_PodStatsRecord =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsPodStatsRecord}, {
      &protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::scc_info_PodStatsRecord_StepBreakdownUsEntry_DoNotUse.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_StepBreakdownEvents.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PodStatsDatabase.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PodStatsRecord_StepBreakdownUsEntry_DoNotUse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PodStatsRecord.base);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tensorflow::profiler::StepBreakdownEvents, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tensorflow::profiler::StepBreakdownEvents, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tensorflow::profiler::StepBreakdownEvents, name_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tensorflow::profiler::PodStatsDatabase, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tensorflow::profiler::PodStatsDatabase, pod_stats_record_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tensorflow::profiler::PodStatsDatabase, diagnostics_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tensorflow::profiler::PodStatsDatabase, step_breakdown_events_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tensorflow::profiler::PodStatsRecord_StepBreakdownUsEntry_DoNotUse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tensorflow::profiler::PodStatsRecord_StepBreakdownUsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tensorflow::profiler::PodStatsRecord_StepBreakdownUsEntry_DoNotUse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tensorflow::profiler::PodStatsRecord_StepBreakdownUsEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tensorflow::profiler::PodStatsRecord, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tensorflow::profiler::PodStatsRecord, host_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tensorflow::profiler::PodStatsRecord, chip_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tensorflow::profiler::PodStatsRecord, node_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tensorflow::profiler::PodStatsRecord, step_num_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tensorflow::profiler::PodStatsRecord, total_duration_us_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tensorflow::profiler::PodStatsRecord, step_breakdown_us_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tensorflow::profiler::PodStatsRecord, bottleneck_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::tensorflow::profiler::StepBreakdownEvents)},
  { 7, -1, sizeof(::tensorflow::profiler::PodStatsDatabase)},
  { 15, 22, sizeof(::tensorflow::profiler::PodStatsRecord_StepBreakdownUsEntry_DoNotUse)},
  { 24, -1, sizeof(::tensorflow::profiler::PodStatsRecord)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::tensorflow::profiler::_StepBreakdownEvents_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::tensorflow::profiler::_PodStatsDatabase_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::tensorflow::profiler::_PodStatsRecord_StepBreakdownUsEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::tensorflow::profiler::_PodStatsRecord_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "tensorflow/core/profiler/protobuf/pod_stats.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n1tensorflow/core/profiler/protobuf/pod_"
      "stats.proto\022\023tensorflow.profiler\0323tensor"
      "flow/core/profiler/protobuf/diagnostics."
      "proto\"/\n\023StepBreakdownEvents\022\n\n\002id\030\001 \001(\005"
      "\022\014\n\004name\030\002 \001(\t\"\327\001\n\020PodStatsDatabase\022=\n\020p"
      "od_stats_record\030\001 \003(\0132#.tensorflow.profi"
      "ler.PodStatsRecord\0225\n\013diagnostics\030\003 \001(\0132"
      " .tensorflow.profiler.Diagnostics\022G\n\025ste"
      "p_breakdown_events\030\004 \003(\0132(.tensorflow.pr"
      "ofiler.StepBreakdownEventsJ\004\010\002\020\003\"\333\002\n\016Pod"
      "StatsRecord\022\021\n\thost_name\030\001 \001(\t\022\017\n\007chip_i"
      "d\030\002 \001(\005\022\017\n\007node_id\030\003 \001(\005\022\020\n\010step_num\030\004 \001"
      "(\r\022\031\n\021total_duration_us\030\005 \001(\001\022S\n\021step_br"
      "eakdown_us\030\023 \003(\01328.tensorflow.profiler.P"
      "odStatsRecord.StepBreakdownUsEntry\022\022\n\nbo"
      "ttleneck\030\016 \001(\t\0326\n\024StepBreakdownUsEntry\022\013"
      "\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\001:\0028\001J\004\010\006\020\007J\004\010\007"
      "\020\010J\004\010\010\020\tJ\004\010\t\020\nJ\004\010\n\020\013J\004\010\013\020\014J\004\010\014\020\rJ\004\010\r\020\016J\004"
      "\010\017\020\020J\004\010\020\020\021J\004\010\021\020\022J\004\010\022\020\023b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 750);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tensorflow/core/profiler/protobuf/pod_stats.proto", &protobuf_RegisterTypes);
  ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fdiagnostics_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto
namespace tensorflow {
namespace profiler {

// ===================================================================

void StepBreakdownEvents::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int StepBreakdownEvents::kIdFieldNumber;
const int StepBreakdownEvents::kNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

StepBreakdownEvents::StepBreakdownEvents()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::scc_info_StepBreakdownEvents.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.profiler.StepBreakdownEvents)
}
StepBreakdownEvents::StepBreakdownEvents(const StepBreakdownEvents& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:tensorflow.profiler.StepBreakdownEvents)
}

void StepBreakdownEvents::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_ = 0;
}

StepBreakdownEvents::~StepBreakdownEvents() {
  // @@protoc_insertion_point(destructor:tensorflow.profiler.StepBreakdownEvents)
  SharedDtor();
}

void StepBreakdownEvents::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void StepBreakdownEvents::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* StepBreakdownEvents::descriptor() {
  ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const StepBreakdownEvents& StepBreakdownEvents::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::scc_info_StepBreakdownEvents.base);
  return *internal_default_instance();
}


void StepBreakdownEvents::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.profiler.StepBreakdownEvents)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_ = 0;
  _internal_metadata_.Clear();
}

bool StepBreakdownEvents::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.profiler.StepBreakdownEvents)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tensorflow.profiler.StepBreakdownEvents.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.profiler.StepBreakdownEvents)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.profiler.StepBreakdownEvents)
  return false;
#undef DO_
}

void StepBreakdownEvents::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.profiler.StepBreakdownEvents)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.profiler.StepBreakdownEvents.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->name(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tensorflow.profiler.StepBreakdownEvents)
}

::google::protobuf::uint8* StepBreakdownEvents::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.profiler.StepBreakdownEvents)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // string name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.profiler.StepBreakdownEvents.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->name(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.profiler.StepBreakdownEvents)
  return target;
}

size_t StepBreakdownEvents::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorflow.profiler.StepBreakdownEvents)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string name = 2;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // int32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void StepBreakdownEvents::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tensorflow.profiler.StepBreakdownEvents)
  GOOGLE_DCHECK_NE(&from, this);
  const StepBreakdownEvents* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const StepBreakdownEvents>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tensorflow.profiler.StepBreakdownEvents)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tensorflow.profiler.StepBreakdownEvents)
    MergeFrom(*source);
  }
}

void StepBreakdownEvents::MergeFrom(const StepBreakdownEvents& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.profiler.StepBreakdownEvents)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.id() != 0) {
    set_id(from.id());
  }
}

void StepBreakdownEvents::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tensorflow.profiler.StepBreakdownEvents)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void StepBreakdownEvents::CopyFrom(const StepBreakdownEvents& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.profiler.StepBreakdownEvents)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StepBreakdownEvents::IsInitialized() const {
  return true;
}

void StepBreakdownEvents::Swap(StepBreakdownEvents* other) {
  if (other == this) return;
  InternalSwap(other);
}
void StepBreakdownEvents::InternalSwap(StepBreakdownEvents* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(id_, other->id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata StepBreakdownEvents::GetMetadata() const {
  protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PodStatsDatabase::InitAsDefaultInstance() {
  ::tensorflow::profiler::_PodStatsDatabase_default_instance_._instance.get_mutable()->diagnostics_ = const_cast< ::tensorflow::profiler::Diagnostics*>(
      ::tensorflow::profiler::Diagnostics::internal_default_instance());
}
void PodStatsDatabase::clear_diagnostics() {
  if (GetArenaNoVirtual() == NULL && diagnostics_ != NULL) {
    delete diagnostics_;
  }
  diagnostics_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PodStatsDatabase::kPodStatsRecordFieldNumber;
const int PodStatsDatabase::kDiagnosticsFieldNumber;
const int PodStatsDatabase::kStepBreakdownEventsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PodStatsDatabase::PodStatsDatabase()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::scc_info_PodStatsDatabase.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.profiler.PodStatsDatabase)
}
PodStatsDatabase::PodStatsDatabase(const PodStatsDatabase& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      pod_stats_record_(from.pod_stats_record_),
      step_breakdown_events_(from.step_breakdown_events_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_diagnostics()) {
    diagnostics_ = new ::tensorflow::profiler::Diagnostics(*from.diagnostics_);
  } else {
    diagnostics_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:tensorflow.profiler.PodStatsDatabase)
}

void PodStatsDatabase::SharedCtor() {
  diagnostics_ = NULL;
}

PodStatsDatabase::~PodStatsDatabase() {
  // @@protoc_insertion_point(destructor:tensorflow.profiler.PodStatsDatabase)
  SharedDtor();
}

void PodStatsDatabase::SharedDtor() {
  if (this != internal_default_instance()) delete diagnostics_;
}

void PodStatsDatabase::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PodStatsDatabase::descriptor() {
  ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PodStatsDatabase& PodStatsDatabase::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::scc_info_PodStatsDatabase.base);
  return *internal_default_instance();
}


void PodStatsDatabase::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.profiler.PodStatsDatabase)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  pod_stats_record_.Clear();
  step_breakdown_events_.Clear();
  if (GetArenaNoVirtual() == NULL && diagnostics_ != NULL) {
    delete diagnostics_;
  }
  diagnostics_ = NULL;
  _internal_metadata_.Clear();
}

bool PodStatsDatabase::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.profiler.PodStatsDatabase)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .tensorflow.profiler.PodStatsRecord pod_stats_record = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_pod_stats_record()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .tensorflow.profiler.Diagnostics diagnostics = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_diagnostics()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .tensorflow.profiler.StepBreakdownEvents step_breakdown_events = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_step_breakdown_events()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.profiler.PodStatsDatabase)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.profiler.PodStatsDatabase)
  return false;
#undef DO_
}

void PodStatsDatabase::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.profiler.PodStatsDatabase)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .tensorflow.profiler.PodStatsRecord pod_stats_record = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->pod_stats_record_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->pod_stats_record(static_cast<int>(i)),
      output);
  }

  // .tensorflow.profiler.Diagnostics diagnostics = 3;
  if (this->has_diagnostics()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->_internal_diagnostics(), output);
  }

  // repeated .tensorflow.profiler.StepBreakdownEvents step_breakdown_events = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->step_breakdown_events_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4,
      this->step_breakdown_events(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tensorflow.profiler.PodStatsDatabase)
}

::google::protobuf::uint8* PodStatsDatabase::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.profiler.PodStatsDatabase)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .tensorflow.profiler.PodStatsRecord pod_stats_record = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->pod_stats_record_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->pod_stats_record(static_cast<int>(i)), deterministic, target);
  }

  // .tensorflow.profiler.Diagnostics diagnostics = 3;
  if (this->has_diagnostics()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->_internal_diagnostics(), deterministic, target);
  }

  // repeated .tensorflow.profiler.StepBreakdownEvents step_breakdown_events = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->step_breakdown_events_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->step_breakdown_events(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.profiler.PodStatsDatabase)
  return target;
}

size_t PodStatsDatabase::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorflow.profiler.PodStatsDatabase)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .tensorflow.profiler.PodStatsRecord pod_stats_record = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->pod_stats_record_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->pod_stats_record(static_cast<int>(i)));
    }
  }

  // repeated .tensorflow.profiler.StepBreakdownEvents step_breakdown_events = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->step_breakdown_events_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->step_breakdown_events(static_cast<int>(i)));
    }
  }

  // .tensorflow.profiler.Diagnostics diagnostics = 3;
  if (this->has_diagnostics()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *diagnostics_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PodStatsDatabase::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tensorflow.profiler.PodStatsDatabase)
  GOOGLE_DCHECK_NE(&from, this);
  const PodStatsDatabase* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PodStatsDatabase>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tensorflow.profiler.PodStatsDatabase)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tensorflow.profiler.PodStatsDatabase)
    MergeFrom(*source);
  }
}

void PodStatsDatabase::MergeFrom(const PodStatsDatabase& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.profiler.PodStatsDatabase)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  pod_stats_record_.MergeFrom(from.pod_stats_record_);
  step_breakdown_events_.MergeFrom(from.step_breakdown_events_);
  if (from.has_diagnostics()) {
    mutable_diagnostics()->::tensorflow::profiler::Diagnostics::MergeFrom(from.diagnostics());
  }
}

void PodStatsDatabase::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tensorflow.profiler.PodStatsDatabase)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PodStatsDatabase::CopyFrom(const PodStatsDatabase& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.profiler.PodStatsDatabase)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PodStatsDatabase::IsInitialized() const {
  return true;
}

void PodStatsDatabase::Swap(PodStatsDatabase* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PodStatsDatabase::InternalSwap(PodStatsDatabase* other) {
  using std::swap;
  CastToBase(&pod_stats_record_)->InternalSwap(CastToBase(&other->pod_stats_record_));
  CastToBase(&step_breakdown_events_)->InternalSwap(CastToBase(&other->step_breakdown_events_));
  swap(diagnostics_, other->diagnostics_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PodStatsDatabase::GetMetadata() const {
  protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

PodStatsRecord_StepBreakdownUsEntry_DoNotUse::PodStatsRecord_StepBreakdownUsEntry_DoNotUse() {}
PodStatsRecord_StepBreakdownUsEntry_DoNotUse::PodStatsRecord_StepBreakdownUsEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
void PodStatsRecord_StepBreakdownUsEntry_DoNotUse::MergeFrom(const PodStatsRecord_StepBreakdownUsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata PodStatsRecord_StepBreakdownUsEntry_DoNotUse::GetMetadata() const {
  ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::file_level_metadata[2];
}
void PodStatsRecord_StepBreakdownUsEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}


// ===================================================================

void PodStatsRecord::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PodStatsRecord::kHostNameFieldNumber;
const int PodStatsRecord::kChipIdFieldNumber;
const int PodStatsRecord::kNodeIdFieldNumber;
const int PodStatsRecord::kStepNumFieldNumber;
const int PodStatsRecord::kTotalDurationUsFieldNumber;
const int PodStatsRecord::kStepBreakdownUsFieldNumber;
const int PodStatsRecord::kBottleneckFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PodStatsRecord::PodStatsRecord()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::scc_info_PodStatsRecord.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.profiler.PodStatsRecord)
}
PodStatsRecord::PodStatsRecord(const PodStatsRecord& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  step_breakdown_us_.MergeFrom(from.step_breakdown_us_);
  host_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.host_name().size() > 0) {
    host_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.host_name_);
  }
  bottleneck_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.bottleneck().size() > 0) {
    bottleneck_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bottleneck_);
  }
  ::memcpy(&chip_id_, &from.chip_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&step_num_) -
    reinterpret_cast<char*>(&chip_id_)) + sizeof(step_num_));
  // @@protoc_insertion_point(copy_constructor:tensorflow.profiler.PodStatsRecord)
}

void PodStatsRecord::SharedCtor() {
  host_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bottleneck_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&chip_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&step_num_) -
      reinterpret_cast<char*>(&chip_id_)) + sizeof(step_num_));
}

PodStatsRecord::~PodStatsRecord() {
  // @@protoc_insertion_point(destructor:tensorflow.profiler.PodStatsRecord)
  SharedDtor();
}

void PodStatsRecord::SharedDtor() {
  host_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bottleneck_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PodStatsRecord::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PodStatsRecord::descriptor() {
  ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PodStatsRecord& PodStatsRecord::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::scc_info_PodStatsRecord.base);
  return *internal_default_instance();
}


void PodStatsRecord::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.profiler.PodStatsRecord)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  step_breakdown_us_.Clear();
  host_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  bottleneck_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&chip_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&step_num_) -
      reinterpret_cast<char*>(&chip_id_)) + sizeof(step_num_));
  _internal_metadata_.Clear();
}

bool PodStatsRecord::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.profiler.PodStatsRecord)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string host_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_host_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->host_name().data(), static_cast<int>(this->host_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tensorflow.profiler.PodStatsRecord.host_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 chip_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &chip_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 node_id = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &node_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 step_num = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &step_num_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double total_duration_us = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(41u /* 41 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &total_duration_us_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string bottleneck = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(114u /* 114 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_bottleneck()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->bottleneck().data(), static_cast<int>(this->bottleneck().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tensorflow.profiler.PodStatsRecord.bottleneck"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // map<int32, double> step_breakdown_us = 19;
      case 19: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(154u /* 154 & 0xFF */)) {
          PodStatsRecord_StepBreakdownUsEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              PodStatsRecord_StepBreakdownUsEntry_DoNotUse,
              ::google::protobuf::int32, double,
              ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
              ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE,
              0 >,
            ::google::protobuf::Map< ::google::protobuf::int32, double > > parser(&step_breakdown_us_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.profiler.PodStatsRecord)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.profiler.PodStatsRecord)
  return false;
#undef DO_
}

void PodStatsRecord::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.profiler.PodStatsRecord)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string host_name = 1;
  if (this->host_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->host_name().data(), static_cast<int>(this->host_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.profiler.PodStatsRecord.host_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->host_name(), output);
  }

  // int32 chip_id = 2;
  if (this->chip_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->chip_id(), output);
  }

  // int32 node_id = 3;
  if (this->node_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->node_id(), output);
  }

  // uint32 step_num = 4;
  if (this->step_num() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->step_num(), output);
  }

  // double total_duration_us = 5;
  if (this->total_duration_us() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->total_duration_us(), output);
  }

  // string bottleneck = 14;
  if (this->bottleneck().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->bottleneck().data(), static_cast<int>(this->bottleneck().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.profiler.PodStatsRecord.bottleneck");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      14, this->bottleneck(), output);
  }

  // map<int32, double> step_breakdown_us = 19;
  if (!this->step_breakdown_us().empty()) {
    typedef ::google::protobuf::Map< ::google::protobuf::int32, double >::const_pointer
        ConstPtr;
    typedef ::google::protobuf::internal::SortItem< ::google::protobuf::int32, ConstPtr > SortItem;
    typedef ::google::protobuf::internal::CompareByFirstField<SortItem> Less;

    if (output->IsSerializationDeterministic() &&
        this->step_breakdown_us().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->step_breakdown_us().size()]);
      typedef ::google::protobuf::Map< ::google::protobuf::int32, double >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::google::protobuf::int32, double >::const_iterator
          it = this->step_breakdown_us().begin();
          it != this->step_breakdown_us().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<PodStatsRecord_StepBreakdownUsEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(step_breakdown_us_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)].second->first, items[static_cast<ptrdiff_t>(i)].second->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            19, *entry, output);
      }
    } else {
      ::std::unique_ptr<PodStatsRecord_StepBreakdownUsEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::google::protobuf::int32, double >::const_iterator
          it = this->step_breakdown_us().begin();
          it != this->step_breakdown_us().end(); ++it) {
        entry.reset(step_breakdown_us_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            19, *entry, output);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tensorflow.profiler.PodStatsRecord)
}

::google::protobuf::uint8* PodStatsRecord::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.profiler.PodStatsRecord)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string host_name = 1;
  if (this->host_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->host_name().data(), static_cast<int>(this->host_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.profiler.PodStatsRecord.host_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->host_name(), target);
  }

  // int32 chip_id = 2;
  if (this->chip_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->chip_id(), target);
  }

  // int32 node_id = 3;
  if (this->node_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->node_id(), target);
  }

  // uint32 step_num = 4;
  if (this->step_num() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->step_num(), target);
  }

  // double total_duration_us = 5;
  if (this->total_duration_us() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->total_duration_us(), target);
  }

  // string bottleneck = 14;
  if (this->bottleneck().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->bottleneck().data(), static_cast<int>(this->bottleneck().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.profiler.PodStatsRecord.bottleneck");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        14, this->bottleneck(), target);
  }

  // map<int32, double> step_breakdown_us = 19;
  if (!this->step_breakdown_us().empty()) {
    typedef ::google::protobuf::Map< ::google::protobuf::int32, double >::const_pointer
        ConstPtr;
    typedef ::google::protobuf::internal::SortItem< ::google::protobuf::int32, ConstPtr > SortItem;
    typedef ::google::protobuf::internal::CompareByFirstField<SortItem> Less;

    if (deterministic &&
        this->step_breakdown_us().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->step_breakdown_us().size()]);
      typedef ::google::protobuf::Map< ::google::protobuf::int32, double >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::google::protobuf::int32, double >::const_iterator
          it = this->step_breakdown_us().begin();
          it != this->step_breakdown_us().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<PodStatsRecord_StepBreakdownUsEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(step_breakdown_us_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)].second->first, items[static_cast<ptrdiff_t>(i)].second->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       19, *entry, deterministic, target);
;
      }
    } else {
      ::std::unique_ptr<PodStatsRecord_StepBreakdownUsEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::google::protobuf::int32, double >::const_iterator
          it = this->step_breakdown_us().begin();
          it != this->step_breakdown_us().end(); ++it) {
        entry.reset(step_breakdown_us_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       19, *entry, deterministic, target);
;
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.profiler.PodStatsRecord)
  return target;
}

size_t PodStatsRecord::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorflow.profiler.PodStatsRecord)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // map<int32, double> step_breakdown_us = 19;
  total_size += 2 *
      ::google::protobuf::internal::FromIntSize(this->step_breakdown_us_size());
  {
    ::std::unique_ptr<PodStatsRecord_StepBreakdownUsEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::google::protobuf::int32, double >::const_iterator
        it = this->step_breakdown_us().begin();
        it != this->step_breakdown_us().end(); ++it) {
      entry.reset(step_breakdown_us_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  // string host_name = 1;
  if (this->host_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->host_name());
  }

  // string bottleneck = 14;
  if (this->bottleneck().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->bottleneck());
  }

  // int32 chip_id = 2;
  if (this->chip_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->chip_id());
  }

  // int32 node_id = 3;
  if (this->node_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->node_id());
  }

  // double total_duration_us = 5;
  if (this->total_duration_us() != 0) {
    total_size += 1 + 8;
  }

  // uint32 step_num = 4;
  if (this->step_num() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->step_num());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PodStatsRecord::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tensorflow.profiler.PodStatsRecord)
  GOOGLE_DCHECK_NE(&from, this);
  const PodStatsRecord* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PodStatsRecord>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tensorflow.profiler.PodStatsRecord)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tensorflow.profiler.PodStatsRecord)
    MergeFrom(*source);
  }
}

void PodStatsRecord::MergeFrom(const PodStatsRecord& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.profiler.PodStatsRecord)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  step_breakdown_us_.MergeFrom(from.step_breakdown_us_);
  if (from.host_name().size() > 0) {

    host_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.host_name_);
  }
  if (from.bottleneck().size() > 0) {

    bottleneck_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.bottleneck_);
  }
  if (from.chip_id() != 0) {
    set_chip_id(from.chip_id());
  }
  if (from.node_id() != 0) {
    set_node_id(from.node_id());
  }
  if (from.total_duration_us() != 0) {
    set_total_duration_us(from.total_duration_us());
  }
  if (from.step_num() != 0) {
    set_step_num(from.step_num());
  }
}

void PodStatsRecord::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tensorflow.profiler.PodStatsRecord)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PodStatsRecord::CopyFrom(const PodStatsRecord& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.profiler.PodStatsRecord)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PodStatsRecord::IsInitialized() const {
  return true;
}

void PodStatsRecord::Swap(PodStatsRecord* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PodStatsRecord::InternalSwap(PodStatsRecord* other) {
  using std::swap;
  step_breakdown_us_.Swap(&other->step_breakdown_us_);
  host_name_.Swap(&other->host_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  bottleneck_.Swap(&other->bottleneck_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(chip_id_, other->chip_id_);
  swap(node_id_, other->node_id_);
  swap(total_duration_us_, other->total_duration_us_);
  swap(step_num_, other->step_num_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PodStatsRecord::GetMetadata() const {
  protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fstats_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace profiler
}  // namespace tensorflow
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::tensorflow::profiler::StepBreakdownEvents* Arena::CreateMaybeMessage< ::tensorflow::profiler::StepBreakdownEvents >(Arena* arena) {
  return Arena::CreateInternal< ::tensorflow::profiler::StepBreakdownEvents >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::tensorflow::profiler::PodStatsDatabase* Arena::CreateMaybeMessage< ::tensorflow::profiler::PodStatsDatabase >(Arena* arena) {
  return Arena::CreateInternal< ::tensorflow::profiler::PodStatsDatabase >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::tensorflow::profiler::PodStatsRecord_StepBreakdownUsEntry_DoNotUse* Arena::CreateMaybeMessage< ::tensorflow::profiler::PodStatsRecord_StepBreakdownUsEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateInternal< ::tensorflow::profiler::PodStatsRecord_StepBreakdownUsEntry_DoNotUse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::tensorflow::profiler::PodStatsRecord* Arena::CreateMaybeMessage< ::tensorflow::profiler::PodStatsRecord >(Arena* arena) {
  return Arena::CreateInternal< ::tensorflow::profiler::PodStatsRecord >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
