// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/profiler/protobuf/pod_viewer.proto

#ifndef PROTOBUF_INCLUDED_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fviewer_2eproto
#define PROTOBUF_INCLUDED_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fviewer_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "tensorflow/core/profiler/protobuf/diagnostics.pb.h"
#include "tensorflow/core/profiler/protobuf/pod_stats.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fviewer_2eproto 

namespace protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fviewer_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[10];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fviewer_2eproto
namespace tensorflow {
namespace profiler {
class AllReduceOpInfo;
class AllReduceOpInfoDefaultTypeInternal;
extern AllReduceOpInfoDefaultTypeInternal _AllReduceOpInfo_default_instance_;
class ChannelInfo;
class ChannelInfoDefaultTypeInternal;
extern ChannelInfoDefaultTypeInternal _ChannelInfo_default_instance_;
class PodStatsMap;
class PodStatsMapDefaultTypeInternal;
extern PodStatsMapDefaultTypeInternal _PodStatsMap_default_instance_;
class PodStatsMap_CoreIdToReplicaIdMapEntry_DoNotUse;
class PodStatsMap_CoreIdToReplicaIdMapEntry_DoNotUseDefaultTypeInternal;
extern PodStatsMap_CoreIdToReplicaIdMapEntry_DoNotUseDefaultTypeInternal _PodStatsMap_CoreIdToReplicaIdMapEntry_DoNotUse_default_instance_;
class PodStatsMap_PodStatsPerCoreEntry_DoNotUse;
class PodStatsMap_PodStatsPerCoreEntry_DoNotUseDefaultTypeInternal;
extern PodStatsMap_PodStatsPerCoreEntry_DoNotUseDefaultTypeInternal _PodStatsMap_PodStatsPerCoreEntry_DoNotUse_default_instance_;
class PodStatsSequence;
class PodStatsSequenceDefaultTypeInternal;
extern PodStatsSequenceDefaultTypeInternal _PodStatsSequence_default_instance_;
class PodViewerDatabase;
class PodViewerDatabaseDefaultTypeInternal;
extern PodViewerDatabaseDefaultTypeInternal _PodViewerDatabase_default_instance_;
class PodViewerSummary;
class PodViewerSummaryDefaultTypeInternal;
extern PodViewerSummaryDefaultTypeInternal _PodViewerSummary_default_instance_;
class PodViewerTopology;
class PodViewerTopologyDefaultTypeInternal;
extern PodViewerTopologyDefaultTypeInternal _PodViewerTopology_default_instance_;
class ReplicaGroup;
class ReplicaGroupDefaultTypeInternal;
extern ReplicaGroupDefaultTypeInternal _ReplicaGroup_default_instance_;
}  // namespace profiler
}  // namespace tensorflow
namespace google {
namespace protobuf {
template<> ::tensorflow::profiler::AllReduceOpInfo* Arena::CreateMaybeMessage<::tensorflow::profiler::AllReduceOpInfo>(Arena*);
template<> ::tensorflow::profiler::ChannelInfo* Arena::CreateMaybeMessage<::tensorflow::profiler::ChannelInfo>(Arena*);
template<> ::tensorflow::profiler::PodStatsMap* Arena::CreateMaybeMessage<::tensorflow::profiler::PodStatsMap>(Arena*);
template<> ::tensorflow::profiler::PodStatsMap_CoreIdToReplicaIdMapEntry_DoNotUse* Arena::CreateMaybeMessage<::tensorflow::profiler::PodStatsMap_CoreIdToReplicaIdMapEntry_DoNotUse>(Arena*);
template<> ::tensorflow::profiler::PodStatsMap_PodStatsPerCoreEntry_DoNotUse* Arena::CreateMaybeMessage<::tensorflow::profiler::PodStatsMap_PodStatsPerCoreEntry_DoNotUse>(Arena*);
template<> ::tensorflow::profiler::PodStatsSequence* Arena::CreateMaybeMessage<::tensorflow::profiler::PodStatsSequence>(Arena*);
template<> ::tensorflow::profiler::PodViewerDatabase* Arena::CreateMaybeMessage<::tensorflow::profiler::PodViewerDatabase>(Arena*);
template<> ::tensorflow::profiler::PodViewerSummary* Arena::CreateMaybeMessage<::tensorflow::profiler::PodViewerSummary>(Arena*);
template<> ::tensorflow::profiler::PodViewerTopology* Arena::CreateMaybeMessage<::tensorflow::profiler::PodViewerTopology>(Arena*);
template<> ::tensorflow::profiler::ReplicaGroup* Arena::CreateMaybeMessage<::tensorflow::profiler::ReplicaGroup>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace tensorflow {
namespace profiler {

// ===================================================================

class ReplicaGroup : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.profiler.ReplicaGroup) */ {
 public:
  ReplicaGroup();
  virtual ~ReplicaGroup();

  ReplicaGroup(const ReplicaGroup& from);

  inline ReplicaGroup& operator=(const ReplicaGroup& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ReplicaGroup(ReplicaGroup&& from) noexcept
    : ReplicaGroup() {
    *this = ::std::move(from);
  }

  inline ReplicaGroup& operator=(ReplicaGroup&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReplicaGroup& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReplicaGroup* internal_default_instance() {
    return reinterpret_cast<const ReplicaGroup*>(
               &_ReplicaGroup_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ReplicaGroup* other);
  friend void swap(ReplicaGroup& a, ReplicaGroup& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReplicaGroup* New() const final {
    return CreateMaybeMessage<ReplicaGroup>(NULL);
  }

  ReplicaGroup* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ReplicaGroup>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ReplicaGroup& from);
  void MergeFrom(const ReplicaGroup& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReplicaGroup* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 replica_ids = 1;
  int replica_ids_size() const;
  void clear_replica_ids();
  static const int kReplicaIdsFieldNumber = 1;
  ::google::protobuf::int64 replica_ids(int index) const;
  void set_replica_ids(int index, ::google::protobuf::int64 value);
  void add_replica_ids(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      replica_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_replica_ids();

  // @@protoc_insertion_point(class_scope:tensorflow.profiler.ReplicaGroup)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > replica_ids_;
  mutable int _replica_ids_cached_byte_size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fviewer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AllReduceOpInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.profiler.AllReduceOpInfo) */ {
 public:
  AllReduceOpInfo();
  virtual ~AllReduceOpInfo();

  AllReduceOpInfo(const AllReduceOpInfo& from);

  inline AllReduceOpInfo& operator=(const AllReduceOpInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AllReduceOpInfo(AllReduceOpInfo&& from) noexcept
    : AllReduceOpInfo() {
    *this = ::std::move(from);
  }

  inline AllReduceOpInfo& operator=(AllReduceOpInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const AllReduceOpInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AllReduceOpInfo* internal_default_instance() {
    return reinterpret_cast<const AllReduceOpInfo*>(
               &_AllReduceOpInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(AllReduceOpInfo* other);
  friend void swap(AllReduceOpInfo& a, AllReduceOpInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AllReduceOpInfo* New() const final {
    return CreateMaybeMessage<AllReduceOpInfo>(NULL);
  }

  AllReduceOpInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AllReduceOpInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AllReduceOpInfo& from);
  void MergeFrom(const AllReduceOpInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AllReduceOpInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .tensorflow.profiler.ReplicaGroup replica_groups = 5;
  int replica_groups_size() const;
  void clear_replica_groups();
  static const int kReplicaGroupsFieldNumber = 5;
  ::tensorflow::profiler::ReplicaGroup* mutable_replica_groups(int index);
  ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::ReplicaGroup >*
      mutable_replica_groups();
  const ::tensorflow::profiler::ReplicaGroup& replica_groups(int index) const;
  ::tensorflow::profiler::ReplicaGroup* add_replica_groups();
  const ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::ReplicaGroup >&
      replica_groups() const;

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string description = 6;
  void clear_description();
  static const int kDescriptionFieldNumber = 6;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  #if LANG_CXX11
  void set_description(::std::string&& value);
  #endif
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // double duration_us = 3;
  void clear_duration_us();
  static const int kDurationUsFieldNumber = 3;
  double duration_us() const;
  void set_duration_us(double value);

  // uint64 data_size = 4;
  void clear_data_size();
  static const int kDataSizeFieldNumber = 4;
  ::google::protobuf::uint64 data_size() const;
  void set_data_size(::google::protobuf::uint64 value);

  // uint32 occurrences = 2;
  void clear_occurrences();
  static const int kOccurrencesFieldNumber = 2;
  ::google::protobuf::uint32 occurrences() const;
  void set_occurrences(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:tensorflow.profiler.AllReduceOpInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::ReplicaGroup > replica_groups_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  double duration_us_;
  ::google::protobuf::uint64 data_size_;
  ::google::protobuf::uint32 occurrences_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fviewer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PodStatsMap_PodStatsPerCoreEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<PodStatsMap_PodStatsPerCoreEntry_DoNotUse, 
    ::google::protobuf::uint32, ::tensorflow::profiler::PodStatsRecord,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<PodStatsMap_PodStatsPerCoreEntry_DoNotUse, 
    ::google::protobuf::uint32, ::tensorflow::profiler::PodStatsRecord,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
    0 > SuperType;
  PodStatsMap_PodStatsPerCoreEntry_DoNotUse();
  PodStatsMap_PodStatsPerCoreEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const PodStatsMap_PodStatsPerCoreEntry_DoNotUse& other);
  static const PodStatsMap_PodStatsPerCoreEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const PodStatsMap_PodStatsPerCoreEntry_DoNotUse*>(&_PodStatsMap_PodStatsPerCoreEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class PodStatsMap_CoreIdToReplicaIdMapEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<PodStatsMap_CoreIdToReplicaIdMapEntry_DoNotUse, 
    ::google::protobuf::uint32, ::google::protobuf::uint32,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<PodStatsMap_CoreIdToReplicaIdMapEntry_DoNotUse, 
    ::google::protobuf::uint32, ::google::protobuf::uint32,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
    0 > SuperType;
  PodStatsMap_CoreIdToReplicaIdMapEntry_DoNotUse();
  PodStatsMap_CoreIdToReplicaIdMapEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const PodStatsMap_CoreIdToReplicaIdMapEntry_DoNotUse& other);
  static const PodStatsMap_CoreIdToReplicaIdMapEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const PodStatsMap_CoreIdToReplicaIdMapEntry_DoNotUse*>(&_PodStatsMap_CoreIdToReplicaIdMapEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class PodStatsMap : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.profiler.PodStatsMap) */ {
 public:
  PodStatsMap();
  virtual ~PodStatsMap();

  PodStatsMap(const PodStatsMap& from);

  inline PodStatsMap& operator=(const PodStatsMap& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PodStatsMap(PodStatsMap&& from) noexcept
    : PodStatsMap() {
    *this = ::std::move(from);
  }

  inline PodStatsMap& operator=(PodStatsMap&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PodStatsMap& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PodStatsMap* internal_default_instance() {
    return reinterpret_cast<const PodStatsMap*>(
               &_PodStatsMap_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(PodStatsMap* other);
  friend void swap(PodStatsMap& a, PodStatsMap& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PodStatsMap* New() const final {
    return CreateMaybeMessage<PodStatsMap>(NULL);
  }

  PodStatsMap* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PodStatsMap>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PodStatsMap& from);
  void MergeFrom(const PodStatsMap& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PodStatsMap* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<uint32, .tensorflow.profiler.PodStatsRecord> pod_stats_per_core = 2;
  int pod_stats_per_core_size() const;
  void clear_pod_stats_per_core();
  static const int kPodStatsPerCoreFieldNumber = 2;
  const ::google::protobuf::Map< ::google::protobuf::uint32, ::tensorflow::profiler::PodStatsRecord >&
      pod_stats_per_core() const;
  ::google::protobuf::Map< ::google::protobuf::uint32, ::tensorflow::profiler::PodStatsRecord >*
      mutable_pod_stats_per_core();

  // repeated .tensorflow.profiler.ChannelInfo channel_db = 3;
  int channel_db_size() const;
  void clear_channel_db();
  static const int kChannelDbFieldNumber = 3;
  ::tensorflow::profiler::ChannelInfo* mutable_channel_db(int index);
  ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::ChannelInfo >*
      mutable_channel_db();
  const ::tensorflow::profiler::ChannelInfo& channel_db(int index) const;
  ::tensorflow::profiler::ChannelInfo* add_channel_db();
  const ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::ChannelInfo >&
      channel_db() const;

  // map<uint32, uint32> core_id_to_replica_id_map = 4;
  int core_id_to_replica_id_map_size() const;
  void clear_core_id_to_replica_id_map();
  static const int kCoreIdToReplicaIdMapFieldNumber = 4;
  const ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >&
      core_id_to_replica_id_map() const;
  ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >*
      mutable_core_id_to_replica_id_map();

  // repeated .tensorflow.profiler.AllReduceOpInfo all_reduce_op_db = 5;
  int all_reduce_op_db_size() const;
  void clear_all_reduce_op_db();
  static const int kAllReduceOpDbFieldNumber = 5;
  ::tensorflow::profiler::AllReduceOpInfo* mutable_all_reduce_op_db(int index);
  ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::AllReduceOpInfo >*
      mutable_all_reduce_op_db();
  const ::tensorflow::profiler::AllReduceOpInfo& all_reduce_op_db(int index) const;
  ::tensorflow::profiler::AllReduceOpInfo* add_all_reduce_op_db();
  const ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::AllReduceOpInfo >&
      all_reduce_op_db() const;

  // uint32 step_num = 1;
  void clear_step_num();
  static const int kStepNumFieldNumber = 1;
  ::google::protobuf::uint32 step_num() const;
  void set_step_num(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:tensorflow.profiler.PodStatsMap)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::MapField<
      PodStatsMap_PodStatsPerCoreEntry_DoNotUse,
      ::google::protobuf::uint32, ::tensorflow::profiler::PodStatsRecord,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > pod_stats_per_core_;
  ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::ChannelInfo > channel_db_;
  ::google::protobuf::internal::MapField<
      PodStatsMap_CoreIdToReplicaIdMapEntry_DoNotUse,
      ::google::protobuf::uint32, ::google::protobuf::uint32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_UINT32,
      0 > core_id_to_replica_id_map_;
  ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::AllReduceOpInfo > all_reduce_op_db_;
  ::google::protobuf::uint32 step_num_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fviewer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PodStatsSequence : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.profiler.PodStatsSequence) */ {
 public:
  PodStatsSequence();
  virtual ~PodStatsSequence();

  PodStatsSequence(const PodStatsSequence& from);

  inline PodStatsSequence& operator=(const PodStatsSequence& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PodStatsSequence(PodStatsSequence&& from) noexcept
    : PodStatsSequence() {
    *this = ::std::move(from);
  }

  inline PodStatsSequence& operator=(PodStatsSequence&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PodStatsSequence& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PodStatsSequence* internal_default_instance() {
    return reinterpret_cast<const PodStatsSequence*>(
               &_PodStatsSequence_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(PodStatsSequence* other);
  friend void swap(PodStatsSequence& a, PodStatsSequence& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PodStatsSequence* New() const final {
    return CreateMaybeMessage<PodStatsSequence>(NULL);
  }

  PodStatsSequence* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PodStatsSequence>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PodStatsSequence& from);
  void MergeFrom(const PodStatsSequence& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PodStatsSequence* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .tensorflow.profiler.PodStatsMap pod_stats_map = 1;
  int pod_stats_map_size() const;
  void clear_pod_stats_map();
  static const int kPodStatsMapFieldNumber = 1;
  ::tensorflow::profiler::PodStatsMap* mutable_pod_stats_map(int index);
  ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::PodStatsMap >*
      mutable_pod_stats_map();
  const ::tensorflow::profiler::PodStatsMap& pod_stats_map(int index) const;
  ::tensorflow::profiler::PodStatsMap* add_pod_stats_map();
  const ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::PodStatsMap >&
      pod_stats_map() const;

  // @@protoc_insertion_point(class_scope:tensorflow.profiler.PodStatsSequence)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::PodStatsMap > pod_stats_map_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fviewer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ChannelInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.profiler.ChannelInfo) */ {
 public:
  ChannelInfo();
  virtual ~ChannelInfo();

  ChannelInfo(const ChannelInfo& from);

  inline ChannelInfo& operator=(const ChannelInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ChannelInfo(ChannelInfo&& from) noexcept
    : ChannelInfo() {
    *this = ::std::move(from);
  }

  inline ChannelInfo& operator=(ChannelInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ChannelInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ChannelInfo* internal_default_instance() {
    return reinterpret_cast<const ChannelInfo*>(
               &_ChannelInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(ChannelInfo* other);
  friend void swap(ChannelInfo& a, ChannelInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ChannelInfo* New() const final {
    return CreateMaybeMessage<ChannelInfo>(NULL);
  }

  ChannelInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ChannelInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ChannelInfo& from);
  void MergeFrom(const ChannelInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChannelInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string hlo_names = 8;
  int hlo_names_size() const;
  void clear_hlo_names();
  static const int kHloNamesFieldNumber = 8;
  const ::std::string& hlo_names(int index) const;
  ::std::string* mutable_hlo_names(int index);
  void set_hlo_names(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_hlo_names(int index, ::std::string&& value);
  #endif
  void set_hlo_names(int index, const char* value);
  void set_hlo_names(int index, const char* value, size_t size);
  ::std::string* add_hlo_names();
  void add_hlo_names(const ::std::string& value);
  #if LANG_CXX11
  void add_hlo_names(::std::string&& value);
  #endif
  void add_hlo_names(const char* value);
  void add_hlo_names(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& hlo_names() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_hlo_names();

  // repeated uint32 src_core_ids = 11;
  int src_core_ids_size() const;
  void clear_src_core_ids();
  static const int kSrcCoreIdsFieldNumber = 11;
  ::google::protobuf::uint32 src_core_ids(int index) const;
  void set_src_core_ids(int index, ::google::protobuf::uint32 value);
  void add_src_core_ids(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      src_core_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_src_core_ids();

  // repeated uint32 dst_core_ids = 12;
  int dst_core_ids_size() const;
  void clear_dst_core_ids();
  static const int kDstCoreIdsFieldNumber = 12;
  ::google::protobuf::uint32 dst_core_ids(int index) const;
  void set_dst_core_ids(int index, ::google::protobuf::uint32 value);
  void add_dst_core_ids(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      dst_core_ids() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_dst_core_ids();

  // string description = 13;
  void clear_description();
  static const int kDescriptionFieldNumber = 13;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  #if LANG_CXX11
  void set_description(::std::string&& value);
  #endif
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // int64 channel_id = 1;
  void clear_channel_id();
  static const int kChannelIdFieldNumber = 1;
  ::google::protobuf::int64 channel_id() const;
  void set_channel_id(::google::protobuf::int64 value);

  // uint64 data_size = 4;
  void clear_data_size();
  static const int kDataSizeFieldNumber = 4;
  ::google::protobuf::uint64 data_size() const;
  void set_data_size(::google::protobuf::uint64 value);

  // double duration_us = 5;
  void clear_duration_us();
  static const int kDurationUsFieldNumber = 5;
  double duration_us() const;
  void set_duration_us(double value);

  // double utilization = 7;
  void clear_utilization();
  static const int kUtilizationFieldNumber = 7;
  double utilization() const;
  void set_utilization(double value);

  // double send_delay_us = 9;
  void clear_send_delay_us();
  static const int kSendDelayUsFieldNumber = 9;
  double send_delay_us() const;
  void set_send_delay_us(double value);

  // uint32 occurrences = 6;
  void clear_occurrences();
  static const int kOccurrencesFieldNumber = 6;
  ::google::protobuf::uint32 occurrences() const;
  void set_occurrences(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:tensorflow.profiler.ChannelInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> hlo_names_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > src_core_ids_;
  mutable int _src_core_ids_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > dst_core_ids_;
  mutable int _dst_core_ids_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  ::google::protobuf::int64 channel_id_;
  ::google::protobuf::uint64 data_size_;
  double duration_us_;
  double utilization_;
  double send_delay_us_;
  ::google::protobuf::uint32 occurrences_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fviewer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PodViewerSummary : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.profiler.PodViewerSummary) */ {
 public:
  PodViewerSummary();
  virtual ~PodViewerSummary();

  PodViewerSummary(const PodViewerSummary& from);

  inline PodViewerSummary& operator=(const PodViewerSummary& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PodViewerSummary(PodViewerSummary&& from) noexcept
    : PodViewerSummary() {
    *this = ::std::move(from);
  }

  inline PodViewerSummary& operator=(PodViewerSummary&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PodViewerSummary& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PodViewerSummary* internal_default_instance() {
    return reinterpret_cast<const PodViewerSummary*>(
               &_PodViewerSummary_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  void Swap(PodViewerSummary* other);
  friend void swap(PodViewerSummary& a, PodViewerSummary& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PodViewerSummary* New() const final {
    return CreateMaybeMessage<PodViewerSummary>(NULL);
  }

  PodViewerSummary* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PodViewerSummary>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PodViewerSummary& from);
  void MergeFrom(const PodViewerSummary& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PodViewerSummary* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string warnings = 1;
  int warnings_size() const;
  void clear_warnings();
  static const int kWarningsFieldNumber = 1;
  const ::std::string& warnings(int index) const;
  ::std::string* mutable_warnings(int index);
  void set_warnings(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_warnings(int index, ::std::string&& value);
  #endif
  void set_warnings(int index, const char* value);
  void set_warnings(int index, const char* value, size_t size);
  ::std::string* add_warnings();
  void add_warnings(const ::std::string& value);
  #if LANG_CXX11
  void add_warnings(::std::string&& value);
  #endif
  void add_warnings(const char* value);
  void add_warnings(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& warnings() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_warnings();

  // @@protoc_insertion_point(class_scope:tensorflow.profiler.PodViewerSummary)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::std::string> warnings_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fviewer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PodViewerTopology : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.profiler.PodViewerTopology) */ {
 public:
  PodViewerTopology();
  virtual ~PodViewerTopology();

  PodViewerTopology(const PodViewerTopology& from);

  inline PodViewerTopology& operator=(const PodViewerTopology& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PodViewerTopology(PodViewerTopology&& from) noexcept
    : PodViewerTopology() {
    *this = ::std::move(from);
  }

  inline PodViewerTopology& operator=(PodViewerTopology&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PodViewerTopology& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PodViewerTopology* internal_default_instance() {
    return reinterpret_cast<const PodViewerTopology*>(
               &_PodViewerTopology_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    8;

  void Swap(PodViewerTopology* other);
  friend void swap(PodViewerTopology& a, PodViewerTopology& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PodViewerTopology* New() const final {
    return CreateMaybeMessage<PodViewerTopology>(NULL);
  }

  PodViewerTopology* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PodViewerTopology>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PodViewerTopology& from);
  void MergeFrom(const PodViewerTopology& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PodViewerTopology* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 x_dimension = 1;
  void clear_x_dimension();
  static const int kXDimensionFieldNumber = 1;
  ::google::protobuf::int32 x_dimension() const;
  void set_x_dimension(::google::protobuf::int32 value);

  // int32 y_dimension = 2;
  void clear_y_dimension();
  static const int kYDimensionFieldNumber = 2;
  ::google::protobuf::int32 y_dimension() const;
  void set_y_dimension(::google::protobuf::int32 value);

  // int32 z_dimension = 3;
  void clear_z_dimension();
  static const int kZDimensionFieldNumber = 3;
  ::google::protobuf::int32 z_dimension() const;
  void set_z_dimension(::google::protobuf::int32 value);

  // int32 host_x_stride = 4;
  void clear_host_x_stride();
  static const int kHostXStrideFieldNumber = 4;
  ::google::protobuf::int32 host_x_stride() const;
  void set_host_x_stride(::google::protobuf::int32 value);

  // int32 host_y_stride = 5;
  void clear_host_y_stride();
  static const int kHostYStrideFieldNumber = 5;
  ::google::protobuf::int32 host_y_stride() const;
  void set_host_y_stride(::google::protobuf::int32 value);

  // int32 host_z_stride = 6;
  void clear_host_z_stride();
  static const int kHostZStrideFieldNumber = 6;
  ::google::protobuf::int32 host_z_stride() const;
  void set_host_z_stride(::google::protobuf::int32 value);

  // int32 num_cores_per_chip = 7;
  void clear_num_cores_per_chip();
  static const int kNumCoresPerChipFieldNumber = 7;
  ::google::protobuf::int32 num_cores_per_chip() const;
  void set_num_cores_per_chip(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:tensorflow.profiler.PodViewerTopology)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 x_dimension_;
  ::google::protobuf::int32 y_dimension_;
  ::google::protobuf::int32 z_dimension_;
  ::google::protobuf::int32 host_x_stride_;
  ::google::protobuf::int32 host_y_stride_;
  ::google::protobuf::int32 host_z_stride_;
  ::google::protobuf::int32 num_cores_per_chip_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fviewer_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PodViewerDatabase : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.profiler.PodViewerDatabase) */ {
 public:
  PodViewerDatabase();
  virtual ~PodViewerDatabase();

  PodViewerDatabase(const PodViewerDatabase& from);

  inline PodViewerDatabase& operator=(const PodViewerDatabase& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PodViewerDatabase(PodViewerDatabase&& from) noexcept
    : PodViewerDatabase() {
    *this = ::std::move(from);
  }

  inline PodViewerDatabase& operator=(PodViewerDatabase&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const PodViewerDatabase& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PodViewerDatabase* internal_default_instance() {
    return reinterpret_cast<const PodViewerDatabase*>(
               &_PodViewerDatabase_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    9;

  void Swap(PodViewerDatabase* other);
  friend void swap(PodViewerDatabase& a, PodViewerDatabase& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PodViewerDatabase* New() const final {
    return CreateMaybeMessage<PodViewerDatabase>(NULL);
  }

  PodViewerDatabase* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<PodViewerDatabase>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const PodViewerDatabase& from);
  void MergeFrom(const PodViewerDatabase& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PodViewerDatabase* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .tensorflow.profiler.StepBreakdownEvents step_breakdown_events = 9;
  int step_breakdown_events_size() const;
  void clear_step_breakdown_events();
  static const int kStepBreakdownEventsFieldNumber = 9;
  ::tensorflow::profiler::StepBreakdownEvents* mutable_step_breakdown_events(int index);
  ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::StepBreakdownEvents >*
      mutable_step_breakdown_events();
  const ::tensorflow::profiler::StepBreakdownEvents& step_breakdown_events(int index) const;
  ::tensorflow::profiler::StepBreakdownEvents* add_step_breakdown_events();
  const ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::StepBreakdownEvents >&
      step_breakdown_events() const;

  // string device_type = 10;
  void clear_device_type();
  static const int kDeviceTypeFieldNumber = 10;
  const ::std::string& device_type() const;
  void set_device_type(const ::std::string& value);
  #if LANG_CXX11
  void set_device_type(::std::string&& value);
  #endif
  void set_device_type(const char* value);
  void set_device_type(const char* value, size_t size);
  ::std::string* mutable_device_type();
  ::std::string* release_device_type();
  void set_allocated_device_type(::std::string* device_type);

  // .tensorflow.profiler.PodStatsSequence pod_stats_sequence = 3;
  bool has_pod_stats_sequence() const;
  void clear_pod_stats_sequence();
  static const int kPodStatsSequenceFieldNumber = 3;
  private:
  const ::tensorflow::profiler::PodStatsSequence& _internal_pod_stats_sequence() const;
  public:
  const ::tensorflow::profiler::PodStatsSequence& pod_stats_sequence() const;
  ::tensorflow::profiler::PodStatsSequence* release_pod_stats_sequence();
  ::tensorflow::profiler::PodStatsSequence* mutable_pod_stats_sequence();
  void set_allocated_pod_stats_sequence(::tensorflow::profiler::PodStatsSequence* pod_stats_sequence);

  // .tensorflow.profiler.PodViewerSummary summary = 7;
  bool has_summary() const;
  void clear_summary();
  static const int kSummaryFieldNumber = 7;
  private:
  const ::tensorflow::profiler::PodViewerSummary& _internal_summary() const;
  public:
  const ::tensorflow::profiler::PodViewerSummary& summary() const;
  ::tensorflow::profiler::PodViewerSummary* release_summary();
  ::tensorflow::profiler::PodViewerSummary* mutable_summary();
  void set_allocated_summary(::tensorflow::profiler::PodViewerSummary* summary);

  // .tensorflow.profiler.Diagnostics diagnostics = 8;
  bool has_diagnostics() const;
  void clear_diagnostics();
  static const int kDiagnosticsFieldNumber = 8;
  private:
  const ::tensorflow::profiler::Diagnostics& _internal_diagnostics() const;
  public:
  const ::tensorflow::profiler::Diagnostics& diagnostics() const;
  ::tensorflow::profiler::Diagnostics* release_diagnostics();
  ::tensorflow::profiler::Diagnostics* mutable_diagnostics();
  void set_allocated_diagnostics(::tensorflow::profiler::Diagnostics* diagnostics);

  // .tensorflow.profiler.PodViewerTopology topology = 11;
  bool has_topology() const;
  void clear_topology();
  static const int kTopologyFieldNumber = 11;
  private:
  const ::tensorflow::profiler::PodViewerTopology& _internal_topology() const;
  public:
  const ::tensorflow::profiler::PodViewerTopology& topology() const;
  ::tensorflow::profiler::PodViewerTopology* release_topology();
  ::tensorflow::profiler::PodViewerTopology* mutable_topology();
  void set_allocated_topology(::tensorflow::profiler::PodViewerTopology* topology);

  // @@protoc_insertion_point(class_scope:tensorflow.profiler.PodViewerDatabase)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::StepBreakdownEvents > step_breakdown_events_;
  ::google::protobuf::internal::ArenaStringPtr device_type_;
  ::tensorflow::profiler::PodStatsSequence* pod_stats_sequence_;
  ::tensorflow::profiler::PodViewerSummary* summary_;
  ::tensorflow::profiler::Diagnostics* diagnostics_;
  ::tensorflow::profiler::PodViewerTopology* topology_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fviewer_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ReplicaGroup

// repeated int64 replica_ids = 1;
inline int ReplicaGroup::replica_ids_size() const {
  return replica_ids_.size();
}
inline void ReplicaGroup::clear_replica_ids() {
  replica_ids_.Clear();
}
inline ::google::protobuf::int64 ReplicaGroup::replica_ids(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.ReplicaGroup.replica_ids)
  return replica_ids_.Get(index);
}
inline void ReplicaGroup::set_replica_ids(int index, ::google::protobuf::int64 value) {
  replica_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:tensorflow.profiler.ReplicaGroup.replica_ids)
}
inline void ReplicaGroup::add_replica_ids(::google::protobuf::int64 value) {
  replica_ids_.Add(value);
  // @@protoc_insertion_point(field_add:tensorflow.profiler.ReplicaGroup.replica_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
ReplicaGroup::replica_ids() const {
  // @@protoc_insertion_point(field_list:tensorflow.profiler.ReplicaGroup.replica_ids)
  return replica_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
ReplicaGroup::mutable_replica_ids() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.profiler.ReplicaGroup.replica_ids)
  return &replica_ids_;
}

// -------------------------------------------------------------------

// AllReduceOpInfo

// string name = 1;
inline void AllReduceOpInfo::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AllReduceOpInfo::name() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.AllReduceOpInfo.name)
  return name_.GetNoArena();
}
inline void AllReduceOpInfo::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tensorflow.profiler.AllReduceOpInfo.name)
}
#if LANG_CXX11
inline void AllReduceOpInfo::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tensorflow.profiler.AllReduceOpInfo.name)
}
#endif
inline void AllReduceOpInfo::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tensorflow.profiler.AllReduceOpInfo.name)
}
inline void AllReduceOpInfo::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tensorflow.profiler.AllReduceOpInfo.name)
}
inline ::std::string* AllReduceOpInfo::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:tensorflow.profiler.AllReduceOpInfo.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AllReduceOpInfo::release_name() {
  // @@protoc_insertion_point(field_release:tensorflow.profiler.AllReduceOpInfo.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AllReduceOpInfo::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:tensorflow.profiler.AllReduceOpInfo.name)
}

// uint32 occurrences = 2;
inline void AllReduceOpInfo::clear_occurrences() {
  occurrences_ = 0u;
}
inline ::google::protobuf::uint32 AllReduceOpInfo::occurrences() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.AllReduceOpInfo.occurrences)
  return occurrences_;
}
inline void AllReduceOpInfo::set_occurrences(::google::protobuf::uint32 value) {
  
  occurrences_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.profiler.AllReduceOpInfo.occurrences)
}

// double duration_us = 3;
inline void AllReduceOpInfo::clear_duration_us() {
  duration_us_ = 0;
}
inline double AllReduceOpInfo::duration_us() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.AllReduceOpInfo.duration_us)
  return duration_us_;
}
inline void AllReduceOpInfo::set_duration_us(double value) {
  
  duration_us_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.profiler.AllReduceOpInfo.duration_us)
}

// uint64 data_size = 4;
inline void AllReduceOpInfo::clear_data_size() {
  data_size_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 AllReduceOpInfo::data_size() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.AllReduceOpInfo.data_size)
  return data_size_;
}
inline void AllReduceOpInfo::set_data_size(::google::protobuf::uint64 value) {
  
  data_size_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.profiler.AllReduceOpInfo.data_size)
}

// repeated .tensorflow.profiler.ReplicaGroup replica_groups = 5;
inline int AllReduceOpInfo::replica_groups_size() const {
  return replica_groups_.size();
}
inline void AllReduceOpInfo::clear_replica_groups() {
  replica_groups_.Clear();
}
inline ::tensorflow::profiler::ReplicaGroup* AllReduceOpInfo::mutable_replica_groups(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.profiler.AllReduceOpInfo.replica_groups)
  return replica_groups_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::ReplicaGroup >*
AllReduceOpInfo::mutable_replica_groups() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.profiler.AllReduceOpInfo.replica_groups)
  return &replica_groups_;
}
inline const ::tensorflow::profiler::ReplicaGroup& AllReduceOpInfo::replica_groups(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.AllReduceOpInfo.replica_groups)
  return replica_groups_.Get(index);
}
inline ::tensorflow::profiler::ReplicaGroup* AllReduceOpInfo::add_replica_groups() {
  // @@protoc_insertion_point(field_add:tensorflow.profiler.AllReduceOpInfo.replica_groups)
  return replica_groups_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::ReplicaGroup >&
AllReduceOpInfo::replica_groups() const {
  // @@protoc_insertion_point(field_list:tensorflow.profiler.AllReduceOpInfo.replica_groups)
  return replica_groups_;
}

// string description = 6;
inline void AllReduceOpInfo::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& AllReduceOpInfo::description() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.AllReduceOpInfo.description)
  return description_.GetNoArena();
}
inline void AllReduceOpInfo::set_description(const ::std::string& value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tensorflow.profiler.AllReduceOpInfo.description)
}
#if LANG_CXX11
inline void AllReduceOpInfo::set_description(::std::string&& value) {
  
  description_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tensorflow.profiler.AllReduceOpInfo.description)
}
#endif
inline void AllReduceOpInfo::set_description(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tensorflow.profiler.AllReduceOpInfo.description)
}
inline void AllReduceOpInfo::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tensorflow.profiler.AllReduceOpInfo.description)
}
inline ::std::string* AllReduceOpInfo::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:tensorflow.profiler.AllReduceOpInfo.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* AllReduceOpInfo::release_description() {
  // @@protoc_insertion_point(field_release:tensorflow.profiler.AllReduceOpInfo.description)
  
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void AllReduceOpInfo::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:tensorflow.profiler.AllReduceOpInfo.description)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// PodStatsMap

// uint32 step_num = 1;
inline void PodStatsMap::clear_step_num() {
  step_num_ = 0u;
}
inline ::google::protobuf::uint32 PodStatsMap::step_num() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.PodStatsMap.step_num)
  return step_num_;
}
inline void PodStatsMap::set_step_num(::google::protobuf::uint32 value) {
  
  step_num_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.profiler.PodStatsMap.step_num)
}

// map<uint32, .tensorflow.profiler.PodStatsRecord> pod_stats_per_core = 2;
inline int PodStatsMap::pod_stats_per_core_size() const {
  return pod_stats_per_core_.size();
}
inline const ::google::protobuf::Map< ::google::protobuf::uint32, ::tensorflow::profiler::PodStatsRecord >&
PodStatsMap::pod_stats_per_core() const {
  // @@protoc_insertion_point(field_map:tensorflow.profiler.PodStatsMap.pod_stats_per_core)
  return pod_stats_per_core_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::uint32, ::tensorflow::profiler::PodStatsRecord >*
PodStatsMap::mutable_pod_stats_per_core() {
  // @@protoc_insertion_point(field_mutable_map:tensorflow.profiler.PodStatsMap.pod_stats_per_core)
  return pod_stats_per_core_.MutableMap();
}

// repeated .tensorflow.profiler.ChannelInfo channel_db = 3;
inline int PodStatsMap::channel_db_size() const {
  return channel_db_.size();
}
inline void PodStatsMap::clear_channel_db() {
  channel_db_.Clear();
}
inline ::tensorflow::profiler::ChannelInfo* PodStatsMap::mutable_channel_db(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.profiler.PodStatsMap.channel_db)
  return channel_db_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::ChannelInfo >*
PodStatsMap::mutable_channel_db() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.profiler.PodStatsMap.channel_db)
  return &channel_db_;
}
inline const ::tensorflow::profiler::ChannelInfo& PodStatsMap::channel_db(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.PodStatsMap.channel_db)
  return channel_db_.Get(index);
}
inline ::tensorflow::profiler::ChannelInfo* PodStatsMap::add_channel_db() {
  // @@protoc_insertion_point(field_add:tensorflow.profiler.PodStatsMap.channel_db)
  return channel_db_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::ChannelInfo >&
PodStatsMap::channel_db() const {
  // @@protoc_insertion_point(field_list:tensorflow.profiler.PodStatsMap.channel_db)
  return channel_db_;
}

// map<uint32, uint32> core_id_to_replica_id_map = 4;
inline int PodStatsMap::core_id_to_replica_id_map_size() const {
  return core_id_to_replica_id_map_.size();
}
inline void PodStatsMap::clear_core_id_to_replica_id_map() {
  core_id_to_replica_id_map_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >&
PodStatsMap::core_id_to_replica_id_map() const {
  // @@protoc_insertion_point(field_map:tensorflow.profiler.PodStatsMap.core_id_to_replica_id_map)
  return core_id_to_replica_id_map_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::uint32, ::google::protobuf::uint32 >*
PodStatsMap::mutable_core_id_to_replica_id_map() {
  // @@protoc_insertion_point(field_mutable_map:tensorflow.profiler.PodStatsMap.core_id_to_replica_id_map)
  return core_id_to_replica_id_map_.MutableMap();
}

// repeated .tensorflow.profiler.AllReduceOpInfo all_reduce_op_db = 5;
inline int PodStatsMap::all_reduce_op_db_size() const {
  return all_reduce_op_db_.size();
}
inline void PodStatsMap::clear_all_reduce_op_db() {
  all_reduce_op_db_.Clear();
}
inline ::tensorflow::profiler::AllReduceOpInfo* PodStatsMap::mutable_all_reduce_op_db(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.profiler.PodStatsMap.all_reduce_op_db)
  return all_reduce_op_db_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::AllReduceOpInfo >*
PodStatsMap::mutable_all_reduce_op_db() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.profiler.PodStatsMap.all_reduce_op_db)
  return &all_reduce_op_db_;
}
inline const ::tensorflow::profiler::AllReduceOpInfo& PodStatsMap::all_reduce_op_db(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.PodStatsMap.all_reduce_op_db)
  return all_reduce_op_db_.Get(index);
}
inline ::tensorflow::profiler::AllReduceOpInfo* PodStatsMap::add_all_reduce_op_db() {
  // @@protoc_insertion_point(field_add:tensorflow.profiler.PodStatsMap.all_reduce_op_db)
  return all_reduce_op_db_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::AllReduceOpInfo >&
PodStatsMap::all_reduce_op_db() const {
  // @@protoc_insertion_point(field_list:tensorflow.profiler.PodStatsMap.all_reduce_op_db)
  return all_reduce_op_db_;
}

// -------------------------------------------------------------------

// PodStatsSequence

// repeated .tensorflow.profiler.PodStatsMap pod_stats_map = 1;
inline int PodStatsSequence::pod_stats_map_size() const {
  return pod_stats_map_.size();
}
inline void PodStatsSequence::clear_pod_stats_map() {
  pod_stats_map_.Clear();
}
inline ::tensorflow::profiler::PodStatsMap* PodStatsSequence::mutable_pod_stats_map(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.profiler.PodStatsSequence.pod_stats_map)
  return pod_stats_map_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::PodStatsMap >*
PodStatsSequence::mutable_pod_stats_map() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.profiler.PodStatsSequence.pod_stats_map)
  return &pod_stats_map_;
}
inline const ::tensorflow::profiler::PodStatsMap& PodStatsSequence::pod_stats_map(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.PodStatsSequence.pod_stats_map)
  return pod_stats_map_.Get(index);
}
inline ::tensorflow::profiler::PodStatsMap* PodStatsSequence::add_pod_stats_map() {
  // @@protoc_insertion_point(field_add:tensorflow.profiler.PodStatsSequence.pod_stats_map)
  return pod_stats_map_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::PodStatsMap >&
PodStatsSequence::pod_stats_map() const {
  // @@protoc_insertion_point(field_list:tensorflow.profiler.PodStatsSequence.pod_stats_map)
  return pod_stats_map_;
}

// -------------------------------------------------------------------

// ChannelInfo

// int64 channel_id = 1;
inline void ChannelInfo::clear_channel_id() {
  channel_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 ChannelInfo::channel_id() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.ChannelInfo.channel_id)
  return channel_id_;
}
inline void ChannelInfo::set_channel_id(::google::protobuf::int64 value) {
  
  channel_id_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.profiler.ChannelInfo.channel_id)
}

// repeated uint32 src_core_ids = 11;
inline int ChannelInfo::src_core_ids_size() const {
  return src_core_ids_.size();
}
inline void ChannelInfo::clear_src_core_ids() {
  src_core_ids_.Clear();
}
inline ::google::protobuf::uint32 ChannelInfo::src_core_ids(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.ChannelInfo.src_core_ids)
  return src_core_ids_.Get(index);
}
inline void ChannelInfo::set_src_core_ids(int index, ::google::protobuf::uint32 value) {
  src_core_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:tensorflow.profiler.ChannelInfo.src_core_ids)
}
inline void ChannelInfo::add_src_core_ids(::google::protobuf::uint32 value) {
  src_core_ids_.Add(value);
  // @@protoc_insertion_point(field_add:tensorflow.profiler.ChannelInfo.src_core_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
ChannelInfo::src_core_ids() const {
  // @@protoc_insertion_point(field_list:tensorflow.profiler.ChannelInfo.src_core_ids)
  return src_core_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
ChannelInfo::mutable_src_core_ids() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.profiler.ChannelInfo.src_core_ids)
  return &src_core_ids_;
}

// repeated uint32 dst_core_ids = 12;
inline int ChannelInfo::dst_core_ids_size() const {
  return dst_core_ids_.size();
}
inline void ChannelInfo::clear_dst_core_ids() {
  dst_core_ids_.Clear();
}
inline ::google::protobuf::uint32 ChannelInfo::dst_core_ids(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.ChannelInfo.dst_core_ids)
  return dst_core_ids_.Get(index);
}
inline void ChannelInfo::set_dst_core_ids(int index, ::google::protobuf::uint32 value) {
  dst_core_ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:tensorflow.profiler.ChannelInfo.dst_core_ids)
}
inline void ChannelInfo::add_dst_core_ids(::google::protobuf::uint32 value) {
  dst_core_ids_.Add(value);
  // @@protoc_insertion_point(field_add:tensorflow.profiler.ChannelInfo.dst_core_ids)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
ChannelInfo::dst_core_ids() const {
  // @@protoc_insertion_point(field_list:tensorflow.profiler.ChannelInfo.dst_core_ids)
  return dst_core_ids_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
ChannelInfo::mutable_dst_core_ids() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.profiler.ChannelInfo.dst_core_ids)
  return &dst_core_ids_;
}

// uint64 data_size = 4;
inline void ChannelInfo::clear_data_size() {
  data_size_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ChannelInfo::data_size() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.ChannelInfo.data_size)
  return data_size_;
}
inline void ChannelInfo::set_data_size(::google::protobuf::uint64 value) {
  
  data_size_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.profiler.ChannelInfo.data_size)
}

// double duration_us = 5;
inline void ChannelInfo::clear_duration_us() {
  duration_us_ = 0;
}
inline double ChannelInfo::duration_us() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.ChannelInfo.duration_us)
  return duration_us_;
}
inline void ChannelInfo::set_duration_us(double value) {
  
  duration_us_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.profiler.ChannelInfo.duration_us)
}

// uint32 occurrences = 6;
inline void ChannelInfo::clear_occurrences() {
  occurrences_ = 0u;
}
inline ::google::protobuf::uint32 ChannelInfo::occurrences() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.ChannelInfo.occurrences)
  return occurrences_;
}
inline void ChannelInfo::set_occurrences(::google::protobuf::uint32 value) {
  
  occurrences_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.profiler.ChannelInfo.occurrences)
}

// double utilization = 7;
inline void ChannelInfo::clear_utilization() {
  utilization_ = 0;
}
inline double ChannelInfo::utilization() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.ChannelInfo.utilization)
  return utilization_;
}
inline void ChannelInfo::set_utilization(double value) {
  
  utilization_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.profiler.ChannelInfo.utilization)
}

// repeated string hlo_names = 8;
inline int ChannelInfo::hlo_names_size() const {
  return hlo_names_.size();
}
inline void ChannelInfo::clear_hlo_names() {
  hlo_names_.Clear();
}
inline const ::std::string& ChannelInfo::hlo_names(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.ChannelInfo.hlo_names)
  return hlo_names_.Get(index);
}
inline ::std::string* ChannelInfo::mutable_hlo_names(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.profiler.ChannelInfo.hlo_names)
  return hlo_names_.Mutable(index);
}
inline void ChannelInfo::set_hlo_names(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:tensorflow.profiler.ChannelInfo.hlo_names)
  hlo_names_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void ChannelInfo::set_hlo_names(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:tensorflow.profiler.ChannelInfo.hlo_names)
  hlo_names_.Mutable(index)->assign(std::move(value));
}
#endif
inline void ChannelInfo::set_hlo_names(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  hlo_names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:tensorflow.profiler.ChannelInfo.hlo_names)
}
inline void ChannelInfo::set_hlo_names(int index, const char* value, size_t size) {
  hlo_names_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:tensorflow.profiler.ChannelInfo.hlo_names)
}
inline ::std::string* ChannelInfo::add_hlo_names() {
  // @@protoc_insertion_point(field_add_mutable:tensorflow.profiler.ChannelInfo.hlo_names)
  return hlo_names_.Add();
}
inline void ChannelInfo::add_hlo_names(const ::std::string& value) {
  hlo_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:tensorflow.profiler.ChannelInfo.hlo_names)
}
#if LANG_CXX11
inline void ChannelInfo::add_hlo_names(::std::string&& value) {
  hlo_names_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:tensorflow.profiler.ChannelInfo.hlo_names)
}
#endif
inline void ChannelInfo::add_hlo_names(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  hlo_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:tensorflow.profiler.ChannelInfo.hlo_names)
}
inline void ChannelInfo::add_hlo_names(const char* value, size_t size) {
  hlo_names_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:tensorflow.profiler.ChannelInfo.hlo_names)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
ChannelInfo::hlo_names() const {
  // @@protoc_insertion_point(field_list:tensorflow.profiler.ChannelInfo.hlo_names)
  return hlo_names_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
ChannelInfo::mutable_hlo_names() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.profiler.ChannelInfo.hlo_names)
  return &hlo_names_;
}

// double send_delay_us = 9;
inline void ChannelInfo::clear_send_delay_us() {
  send_delay_us_ = 0;
}
inline double ChannelInfo::send_delay_us() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.ChannelInfo.send_delay_us)
  return send_delay_us_;
}
inline void ChannelInfo::set_send_delay_us(double value) {
  
  send_delay_us_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.profiler.ChannelInfo.send_delay_us)
}

// string description = 13;
inline void ChannelInfo::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ChannelInfo::description() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.ChannelInfo.description)
  return description_.GetNoArena();
}
inline void ChannelInfo::set_description(const ::std::string& value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tensorflow.profiler.ChannelInfo.description)
}
#if LANG_CXX11
inline void ChannelInfo::set_description(::std::string&& value) {
  
  description_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tensorflow.profiler.ChannelInfo.description)
}
#endif
inline void ChannelInfo::set_description(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tensorflow.profiler.ChannelInfo.description)
}
inline void ChannelInfo::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tensorflow.profiler.ChannelInfo.description)
}
inline ::std::string* ChannelInfo::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:tensorflow.profiler.ChannelInfo.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ChannelInfo::release_description() {
  // @@protoc_insertion_point(field_release:tensorflow.profiler.ChannelInfo.description)
  
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ChannelInfo::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:tensorflow.profiler.ChannelInfo.description)
}

// -------------------------------------------------------------------

// PodViewerSummary

// repeated string warnings = 1;
inline int PodViewerSummary::warnings_size() const {
  return warnings_.size();
}
inline void PodViewerSummary::clear_warnings() {
  warnings_.Clear();
}
inline const ::std::string& PodViewerSummary::warnings(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.PodViewerSummary.warnings)
  return warnings_.Get(index);
}
inline ::std::string* PodViewerSummary::mutable_warnings(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.profiler.PodViewerSummary.warnings)
  return warnings_.Mutable(index);
}
inline void PodViewerSummary::set_warnings(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:tensorflow.profiler.PodViewerSummary.warnings)
  warnings_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void PodViewerSummary::set_warnings(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:tensorflow.profiler.PodViewerSummary.warnings)
  warnings_.Mutable(index)->assign(std::move(value));
}
#endif
inline void PodViewerSummary::set_warnings(int index, const char* value) {
  GOOGLE_DCHECK(value != NULL);
  warnings_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:tensorflow.profiler.PodViewerSummary.warnings)
}
inline void PodViewerSummary::set_warnings(int index, const char* value, size_t size) {
  warnings_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:tensorflow.profiler.PodViewerSummary.warnings)
}
inline ::std::string* PodViewerSummary::add_warnings() {
  // @@protoc_insertion_point(field_add_mutable:tensorflow.profiler.PodViewerSummary.warnings)
  return warnings_.Add();
}
inline void PodViewerSummary::add_warnings(const ::std::string& value) {
  warnings_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:tensorflow.profiler.PodViewerSummary.warnings)
}
#if LANG_CXX11
inline void PodViewerSummary::add_warnings(::std::string&& value) {
  warnings_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:tensorflow.profiler.PodViewerSummary.warnings)
}
#endif
inline void PodViewerSummary::add_warnings(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  warnings_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:tensorflow.profiler.PodViewerSummary.warnings)
}
inline void PodViewerSummary::add_warnings(const char* value, size_t size) {
  warnings_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:tensorflow.profiler.PodViewerSummary.warnings)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
PodViewerSummary::warnings() const {
  // @@protoc_insertion_point(field_list:tensorflow.profiler.PodViewerSummary.warnings)
  return warnings_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
PodViewerSummary::mutable_warnings() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.profiler.PodViewerSummary.warnings)
  return &warnings_;
}

// -------------------------------------------------------------------

// PodViewerTopology

// int32 x_dimension = 1;
inline void PodViewerTopology::clear_x_dimension() {
  x_dimension_ = 0;
}
inline ::google::protobuf::int32 PodViewerTopology::x_dimension() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.PodViewerTopology.x_dimension)
  return x_dimension_;
}
inline void PodViewerTopology::set_x_dimension(::google::protobuf::int32 value) {
  
  x_dimension_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.profiler.PodViewerTopology.x_dimension)
}

// int32 y_dimension = 2;
inline void PodViewerTopology::clear_y_dimension() {
  y_dimension_ = 0;
}
inline ::google::protobuf::int32 PodViewerTopology::y_dimension() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.PodViewerTopology.y_dimension)
  return y_dimension_;
}
inline void PodViewerTopology::set_y_dimension(::google::protobuf::int32 value) {
  
  y_dimension_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.profiler.PodViewerTopology.y_dimension)
}

// int32 z_dimension = 3;
inline void PodViewerTopology::clear_z_dimension() {
  z_dimension_ = 0;
}
inline ::google::protobuf::int32 PodViewerTopology::z_dimension() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.PodViewerTopology.z_dimension)
  return z_dimension_;
}
inline void PodViewerTopology::set_z_dimension(::google::protobuf::int32 value) {
  
  z_dimension_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.profiler.PodViewerTopology.z_dimension)
}

// int32 host_x_stride = 4;
inline void PodViewerTopology::clear_host_x_stride() {
  host_x_stride_ = 0;
}
inline ::google::protobuf::int32 PodViewerTopology::host_x_stride() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.PodViewerTopology.host_x_stride)
  return host_x_stride_;
}
inline void PodViewerTopology::set_host_x_stride(::google::protobuf::int32 value) {
  
  host_x_stride_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.profiler.PodViewerTopology.host_x_stride)
}

// int32 host_y_stride = 5;
inline void PodViewerTopology::clear_host_y_stride() {
  host_y_stride_ = 0;
}
inline ::google::protobuf::int32 PodViewerTopology::host_y_stride() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.PodViewerTopology.host_y_stride)
  return host_y_stride_;
}
inline void PodViewerTopology::set_host_y_stride(::google::protobuf::int32 value) {
  
  host_y_stride_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.profiler.PodViewerTopology.host_y_stride)
}

// int32 host_z_stride = 6;
inline void PodViewerTopology::clear_host_z_stride() {
  host_z_stride_ = 0;
}
inline ::google::protobuf::int32 PodViewerTopology::host_z_stride() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.PodViewerTopology.host_z_stride)
  return host_z_stride_;
}
inline void PodViewerTopology::set_host_z_stride(::google::protobuf::int32 value) {
  
  host_z_stride_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.profiler.PodViewerTopology.host_z_stride)
}

// int32 num_cores_per_chip = 7;
inline void PodViewerTopology::clear_num_cores_per_chip() {
  num_cores_per_chip_ = 0;
}
inline ::google::protobuf::int32 PodViewerTopology::num_cores_per_chip() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.PodViewerTopology.num_cores_per_chip)
  return num_cores_per_chip_;
}
inline void PodViewerTopology::set_num_cores_per_chip(::google::protobuf::int32 value) {
  
  num_cores_per_chip_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.profiler.PodViewerTopology.num_cores_per_chip)
}

// -------------------------------------------------------------------

// PodViewerDatabase

// string device_type = 10;
inline void PodViewerDatabase::clear_device_type() {
  device_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PodViewerDatabase::device_type() const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.PodViewerDatabase.device_type)
  return device_type_.GetNoArena();
}
inline void PodViewerDatabase::set_device_type(const ::std::string& value) {
  
  device_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tensorflow.profiler.PodViewerDatabase.device_type)
}
#if LANG_CXX11
inline void PodViewerDatabase::set_device_type(::std::string&& value) {
  
  device_type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tensorflow.profiler.PodViewerDatabase.device_type)
}
#endif
inline void PodViewerDatabase::set_device_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  device_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tensorflow.profiler.PodViewerDatabase.device_type)
}
inline void PodViewerDatabase::set_device_type(const char* value, size_t size) {
  
  device_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tensorflow.profiler.PodViewerDatabase.device_type)
}
inline ::std::string* PodViewerDatabase::mutable_device_type() {
  
  // @@protoc_insertion_point(field_mutable:tensorflow.profiler.PodViewerDatabase.device_type)
  return device_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PodViewerDatabase::release_device_type() {
  // @@protoc_insertion_point(field_release:tensorflow.profiler.PodViewerDatabase.device_type)
  
  return device_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PodViewerDatabase::set_allocated_device_type(::std::string* device_type) {
  if (device_type != NULL) {
    
  } else {
    
  }
  device_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), device_type);
  // @@protoc_insertion_point(field_set_allocated:tensorflow.profiler.PodViewerDatabase.device_type)
}

// .tensorflow.profiler.PodStatsSequence pod_stats_sequence = 3;
inline bool PodViewerDatabase::has_pod_stats_sequence() const {
  return this != internal_default_instance() && pod_stats_sequence_ != NULL;
}
inline void PodViewerDatabase::clear_pod_stats_sequence() {
  if (GetArenaNoVirtual() == NULL && pod_stats_sequence_ != NULL) {
    delete pod_stats_sequence_;
  }
  pod_stats_sequence_ = NULL;
}
inline const ::tensorflow::profiler::PodStatsSequence& PodViewerDatabase::_internal_pod_stats_sequence() const {
  return *pod_stats_sequence_;
}
inline const ::tensorflow::profiler::PodStatsSequence& PodViewerDatabase::pod_stats_sequence() const {
  const ::tensorflow::profiler::PodStatsSequence* p = pod_stats_sequence_;
  // @@protoc_insertion_point(field_get:tensorflow.profiler.PodViewerDatabase.pod_stats_sequence)
  return p != NULL ? *p : *reinterpret_cast<const ::tensorflow::profiler::PodStatsSequence*>(
      &::tensorflow::profiler::_PodStatsSequence_default_instance_);
}
inline ::tensorflow::profiler::PodStatsSequence* PodViewerDatabase::release_pod_stats_sequence() {
  // @@protoc_insertion_point(field_release:tensorflow.profiler.PodViewerDatabase.pod_stats_sequence)
  
  ::tensorflow::profiler::PodStatsSequence* temp = pod_stats_sequence_;
  pod_stats_sequence_ = NULL;
  return temp;
}
inline ::tensorflow::profiler::PodStatsSequence* PodViewerDatabase::mutable_pod_stats_sequence() {
  
  if (pod_stats_sequence_ == NULL) {
    auto* p = CreateMaybeMessage<::tensorflow::profiler::PodStatsSequence>(GetArenaNoVirtual());
    pod_stats_sequence_ = p;
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.profiler.PodViewerDatabase.pod_stats_sequence)
  return pod_stats_sequence_;
}
inline void PodViewerDatabase::set_allocated_pod_stats_sequence(::tensorflow::profiler::PodStatsSequence* pod_stats_sequence) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete pod_stats_sequence_;
  }
  if (pod_stats_sequence) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      pod_stats_sequence = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, pod_stats_sequence, submessage_arena);
    }
    
  } else {
    
  }
  pod_stats_sequence_ = pod_stats_sequence;
  // @@protoc_insertion_point(field_set_allocated:tensorflow.profiler.PodViewerDatabase.pod_stats_sequence)
}

// .tensorflow.profiler.PodViewerSummary summary = 7;
inline bool PodViewerDatabase::has_summary() const {
  return this != internal_default_instance() && summary_ != NULL;
}
inline void PodViewerDatabase::clear_summary() {
  if (GetArenaNoVirtual() == NULL && summary_ != NULL) {
    delete summary_;
  }
  summary_ = NULL;
}
inline const ::tensorflow::profiler::PodViewerSummary& PodViewerDatabase::_internal_summary() const {
  return *summary_;
}
inline const ::tensorflow::profiler::PodViewerSummary& PodViewerDatabase::summary() const {
  const ::tensorflow::profiler::PodViewerSummary* p = summary_;
  // @@protoc_insertion_point(field_get:tensorflow.profiler.PodViewerDatabase.summary)
  return p != NULL ? *p : *reinterpret_cast<const ::tensorflow::profiler::PodViewerSummary*>(
      &::tensorflow::profiler::_PodViewerSummary_default_instance_);
}
inline ::tensorflow::profiler::PodViewerSummary* PodViewerDatabase::release_summary() {
  // @@protoc_insertion_point(field_release:tensorflow.profiler.PodViewerDatabase.summary)
  
  ::tensorflow::profiler::PodViewerSummary* temp = summary_;
  summary_ = NULL;
  return temp;
}
inline ::tensorflow::profiler::PodViewerSummary* PodViewerDatabase::mutable_summary() {
  
  if (summary_ == NULL) {
    auto* p = CreateMaybeMessage<::tensorflow::profiler::PodViewerSummary>(GetArenaNoVirtual());
    summary_ = p;
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.profiler.PodViewerDatabase.summary)
  return summary_;
}
inline void PodViewerDatabase::set_allocated_summary(::tensorflow::profiler::PodViewerSummary* summary) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete summary_;
  }
  if (summary) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      summary = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, summary, submessage_arena);
    }
    
  } else {
    
  }
  summary_ = summary;
  // @@protoc_insertion_point(field_set_allocated:tensorflow.profiler.PodViewerDatabase.summary)
}

// .tensorflow.profiler.Diagnostics diagnostics = 8;
inline bool PodViewerDatabase::has_diagnostics() const {
  return this != internal_default_instance() && diagnostics_ != NULL;
}
inline const ::tensorflow::profiler::Diagnostics& PodViewerDatabase::_internal_diagnostics() const {
  return *diagnostics_;
}
inline const ::tensorflow::profiler::Diagnostics& PodViewerDatabase::diagnostics() const {
  const ::tensorflow::profiler::Diagnostics* p = diagnostics_;
  // @@protoc_insertion_point(field_get:tensorflow.profiler.PodViewerDatabase.diagnostics)
  return p != NULL ? *p : *reinterpret_cast<const ::tensorflow::profiler::Diagnostics*>(
      &::tensorflow::profiler::_Diagnostics_default_instance_);
}
inline ::tensorflow::profiler::Diagnostics* PodViewerDatabase::release_diagnostics() {
  // @@protoc_insertion_point(field_release:tensorflow.profiler.PodViewerDatabase.diagnostics)
  
  ::tensorflow::profiler::Diagnostics* temp = diagnostics_;
  diagnostics_ = NULL;
  return temp;
}
inline ::tensorflow::profiler::Diagnostics* PodViewerDatabase::mutable_diagnostics() {
  
  if (diagnostics_ == NULL) {
    auto* p = CreateMaybeMessage<::tensorflow::profiler::Diagnostics>(GetArenaNoVirtual());
    diagnostics_ = p;
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.profiler.PodViewerDatabase.diagnostics)
  return diagnostics_;
}
inline void PodViewerDatabase::set_allocated_diagnostics(::tensorflow::profiler::Diagnostics* diagnostics) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(diagnostics_);
  }
  if (diagnostics) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      diagnostics = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, diagnostics, submessage_arena);
    }
    
  } else {
    
  }
  diagnostics_ = diagnostics;
  // @@protoc_insertion_point(field_set_allocated:tensorflow.profiler.PodViewerDatabase.diagnostics)
}

// repeated .tensorflow.profiler.StepBreakdownEvents step_breakdown_events = 9;
inline int PodViewerDatabase::step_breakdown_events_size() const {
  return step_breakdown_events_.size();
}
inline ::tensorflow::profiler::StepBreakdownEvents* PodViewerDatabase::mutable_step_breakdown_events(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.profiler.PodViewerDatabase.step_breakdown_events)
  return step_breakdown_events_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::StepBreakdownEvents >*
PodViewerDatabase::mutable_step_breakdown_events() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.profiler.PodViewerDatabase.step_breakdown_events)
  return &step_breakdown_events_;
}
inline const ::tensorflow::profiler::StepBreakdownEvents& PodViewerDatabase::step_breakdown_events(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.profiler.PodViewerDatabase.step_breakdown_events)
  return step_breakdown_events_.Get(index);
}
inline ::tensorflow::profiler::StepBreakdownEvents* PodViewerDatabase::add_step_breakdown_events() {
  // @@protoc_insertion_point(field_add:tensorflow.profiler.PodViewerDatabase.step_breakdown_events)
  return step_breakdown_events_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::tensorflow::profiler::StepBreakdownEvents >&
PodViewerDatabase::step_breakdown_events() const {
  // @@protoc_insertion_point(field_list:tensorflow.profiler.PodViewerDatabase.step_breakdown_events)
  return step_breakdown_events_;
}

// .tensorflow.profiler.PodViewerTopology topology = 11;
inline bool PodViewerDatabase::has_topology() const {
  return this != internal_default_instance() && topology_ != NULL;
}
inline void PodViewerDatabase::clear_topology() {
  if (GetArenaNoVirtual() == NULL && topology_ != NULL) {
    delete topology_;
  }
  topology_ = NULL;
}
inline const ::tensorflow::profiler::PodViewerTopology& PodViewerDatabase::_internal_topology() const {
  return *topology_;
}
inline const ::tensorflow::profiler::PodViewerTopology& PodViewerDatabase::topology() const {
  const ::tensorflow::profiler::PodViewerTopology* p = topology_;
  // @@protoc_insertion_point(field_get:tensorflow.profiler.PodViewerDatabase.topology)
  return p != NULL ? *p : *reinterpret_cast<const ::tensorflow::profiler::PodViewerTopology*>(
      &::tensorflow::profiler::_PodViewerTopology_default_instance_);
}
inline ::tensorflow::profiler::PodViewerTopology* PodViewerDatabase::release_topology() {
  // @@protoc_insertion_point(field_release:tensorflow.profiler.PodViewerDatabase.topology)
  
  ::tensorflow::profiler::PodViewerTopology* temp = topology_;
  topology_ = NULL;
  return temp;
}
inline ::tensorflow::profiler::PodViewerTopology* PodViewerDatabase::mutable_topology() {
  
  if (topology_ == NULL) {
    auto* p = CreateMaybeMessage<::tensorflow::profiler::PodViewerTopology>(GetArenaNoVirtual());
    topology_ = p;
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.profiler.PodViewerDatabase.topology)
  return topology_;
}
inline void PodViewerDatabase::set_allocated_topology(::tensorflow::profiler::PodViewerTopology* topology) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete topology_;
  }
  if (topology) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      topology = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, topology, submessage_arena);
    }
    
  } else {
    
  }
  topology_ = topology;
  // @@protoc_insertion_point(field_set_allocated:tensorflow.profiler.PodViewerDatabase.topology)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace profiler
}  // namespace tensorflow

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_tensorflow_2fcore_2fprofiler_2fprotobuf_2fpod_5fviewer_2eproto
