// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/compiler/xla/service/hlo_execution_profile_data.proto

#ifndef PROTOBUF_INCLUDED_tensorflow_2fcompiler_2fxla_2fservice_2fhlo_5fexecution_5fprofile_5fdata_2eproto
#define PROTOBUF_INCLUDED_tensorflow_2fcompiler_2fxla_2fservice_2fhlo_5fexecution_5fprofile_5fdata_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "tensorflow/compiler/xla/service/hlo_profile_printer_data.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_tensorflow_2fcompiler_2fxla_2fservice_2fhlo_5fexecution_5fprofile_5fdata_2eproto 

namespace protobuf_tensorflow_2fcompiler_2fxla_2fservice_2fhlo_5fexecution_5fprofile_5fdata_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_tensorflow_2fcompiler_2fxla_2fservice_2fhlo_5fexecution_5fprofile_5fdata_2eproto
namespace xla {
class HloExecutionProfileData;
class HloExecutionProfileDataDefaultTypeInternal;
extern HloExecutionProfileDataDefaultTypeInternal _HloExecutionProfileData_default_instance_;
}  // namespace xla
namespace google {
namespace protobuf {
template<> ::xla::HloExecutionProfileData* Arena::CreateMaybeMessage<::xla::HloExecutionProfileData>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace xla {

// ===================================================================

class HloExecutionProfileData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:xla.HloExecutionProfileData) */ {
 public:
  HloExecutionProfileData();
  virtual ~HloExecutionProfileData();

  HloExecutionProfileData(const HloExecutionProfileData& from);

  inline HloExecutionProfileData& operator=(const HloExecutionProfileData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  HloExecutionProfileData(HloExecutionProfileData&& from) noexcept
    : HloExecutionProfileData() {
    *this = ::std::move(from);
  }

  inline HloExecutionProfileData& operator=(HloExecutionProfileData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobuf::Arena* GetArena() const final {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const final {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const HloExecutionProfileData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const HloExecutionProfileData* internal_default_instance() {
    return reinterpret_cast<const HloExecutionProfileData*>(
               &_HloExecutionProfileData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void UnsafeArenaSwap(HloExecutionProfileData* other);
  void Swap(HloExecutionProfileData* other);
  friend void swap(HloExecutionProfileData& a, HloExecutionProfileData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline HloExecutionProfileData* New() const final {
    return CreateMaybeMessage<HloExecutionProfileData>(NULL);
  }

  HloExecutionProfileData* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<HloExecutionProfileData>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const HloExecutionProfileData& from);
  void MergeFrom(const HloExecutionProfileData& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HloExecutionProfileData* other);
  protected:
  explicit HloExecutionProfileData(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int64 profile_counters = 2;
  int profile_counters_size() const;
  void clear_profile_counters();
  static const int kProfileCountersFieldNumber = 2;
  ::google::protobuf::int64 profile_counters(int index) const;
  void set_profile_counters(int index, ::google::protobuf::int64 value);
  void add_profile_counters(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      profile_counters() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_profile_counters();

  // .xla.HloProfilePrinterData printer_data = 1;
  bool has_printer_data() const;
  void clear_printer_data();
  static const int kPrinterDataFieldNumber = 1;
  private:
  const ::xla::HloProfilePrinterData& _internal_printer_data() const;
  public:
  const ::xla::HloProfilePrinterData& printer_data() const;
  ::xla::HloProfilePrinterData* release_printer_data();
  ::xla::HloProfilePrinterData* mutable_printer_data();
  void set_allocated_printer_data(::xla::HloProfilePrinterData* printer_data);
  void unsafe_arena_set_allocated_printer_data(
      ::xla::HloProfilePrinterData* printer_data);
  ::xla::HloProfilePrinterData* unsafe_arena_release_printer_data();

  // @@protoc_insertion_point(class_scope:xla.HloExecutionProfileData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > profile_counters_;
  mutable int _profile_counters_cached_byte_size_;
  ::xla::HloProfilePrinterData* printer_data_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_tensorflow_2fcompiler_2fxla_2fservice_2fhlo_5fexecution_5fprofile_5fdata_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HloExecutionProfileData

// .xla.HloProfilePrinterData printer_data = 1;
inline bool HloExecutionProfileData::has_printer_data() const {
  return this != internal_default_instance() && printer_data_ != NULL;
}
inline const ::xla::HloProfilePrinterData& HloExecutionProfileData::_internal_printer_data() const {
  return *printer_data_;
}
inline const ::xla::HloProfilePrinterData& HloExecutionProfileData::printer_data() const {
  const ::xla::HloProfilePrinterData* p = printer_data_;
  // @@protoc_insertion_point(field_get:xla.HloExecutionProfileData.printer_data)
  return p != NULL ? *p : *reinterpret_cast<const ::xla::HloProfilePrinterData*>(
      &::xla::_HloProfilePrinterData_default_instance_);
}
inline ::xla::HloProfilePrinterData* HloExecutionProfileData::release_printer_data() {
  // @@protoc_insertion_point(field_release:xla.HloExecutionProfileData.printer_data)
  
  ::xla::HloProfilePrinterData* temp = printer_data_;
  if (GetArenaNoVirtual() != NULL) {
    temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
  }
  printer_data_ = NULL;
  return temp;
}
inline ::xla::HloProfilePrinterData* HloExecutionProfileData::unsafe_arena_release_printer_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:xla.HloExecutionProfileData.printer_data)
  
  ::xla::HloProfilePrinterData* temp = printer_data_;
  printer_data_ = NULL;
  return temp;
}
inline ::xla::HloProfilePrinterData* HloExecutionProfileData::mutable_printer_data() {
  
  if (printer_data_ == NULL) {
    auto* p = CreateMaybeMessage<::xla::HloProfilePrinterData>(GetArenaNoVirtual());
    printer_data_ = p;
  }
  // @@protoc_insertion_point(field_mutable:xla.HloExecutionProfileData.printer_data)
  return printer_data_;
}
inline void HloExecutionProfileData::set_allocated_printer_data(::xla::HloProfilePrinterData* printer_data) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(printer_data_);
  }
  if (printer_data) {
    ::google::protobuf::Arena* submessage_arena =
      reinterpret_cast<::google::protobuf::MessageLite*>(printer_data)->GetArena();
    if (message_arena != submessage_arena) {
      printer_data = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, printer_data, submessage_arena);
    }
    
  } else {
    
  }
  printer_data_ = printer_data;
  // @@protoc_insertion_point(field_set_allocated:xla.HloExecutionProfileData.printer_data)
}

// repeated int64 profile_counters = 2;
inline int HloExecutionProfileData::profile_counters_size() const {
  return profile_counters_.size();
}
inline void HloExecutionProfileData::clear_profile_counters() {
  profile_counters_.Clear();
}
inline ::google::protobuf::int64 HloExecutionProfileData::profile_counters(int index) const {
  // @@protoc_insertion_point(field_get:xla.HloExecutionProfileData.profile_counters)
  return profile_counters_.Get(index);
}
inline void HloExecutionProfileData::set_profile_counters(int index, ::google::protobuf::int64 value) {
  profile_counters_.Set(index, value);
  // @@protoc_insertion_point(field_set:xla.HloExecutionProfileData.profile_counters)
}
inline void HloExecutionProfileData::add_profile_counters(::google::protobuf::int64 value) {
  profile_counters_.Add(value);
  // @@protoc_insertion_point(field_add:xla.HloExecutionProfileData.profile_counters)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
HloExecutionProfileData::profile_counters() const {
  // @@protoc_insertion_point(field_list:xla.HloExecutionProfileData.profile_counters)
  return profile_counters_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
HloExecutionProfileData::mutable_profile_counters() {
  // @@protoc_insertion_point(field_mutable_list:xla.HloExecutionProfileData.profile_counters)
  return &profile_counters_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace xla

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_tensorflow_2fcompiler_2fxla_2fservice_2fhlo_5fexecution_5fprofile_5fdata_2eproto
