// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: tensorflow/lite/experimental/acceleration/configuration/configuration.proto
// Original file comments:
// Copyright 2020 The TensorFlow Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// WARNING: Until b/191428000 is fixed you need to manually generate and update
// the generated flatbuffer code when modifying this file. See BUILD for more
// information.
//
// This schema defines how to configure TFLite for delegation. These
// definitions can be used in multiple ways: as output of a compatibility list,
// in benchmarking tools and to decouple delegate instantiation from code.
//
// The schema is work-in-progress, covering the most broadly used delegates and
// options.
//
#ifndef GRPC_tensorflow_2flite_2fexperimental_2facceleration_2fconfiguration_2fconfiguration_2eproto__INCLUDED
#define GRPC_tensorflow_2flite_2fexperimental_2facceleration_2fconfiguration_2fconfiguration_2eproto__INCLUDED

#include "tensorflow/lite/experimental/acceleration/configuration/configuration.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace tflite {
namespace proto {

}  // namespace proto
}  // namespace tflite


#endif  // GRPC_tensorflow_2flite_2fexperimental_2facceleration_2fconfiguration_2fconfiguration_2eproto__INCLUDED
