// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: tensorflow/core/util/example_proto_fast_parsing_test.proto
// Original file comments:
// Protocol message for the fast Example parse unit test.
#ifndef GRPC_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto__INCLUDED
#define GRPC_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto__INCLUDED

#include "tensorflow/core/util/example_proto_fast_parsing_test.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace tensorflow {

}  // namespace tensorflow


#endif  // GRPC_tensorflow_2fcore_2futil_2fexample_5fproto_5ffast_5fparsing_5ftest_2eproto__INCLUDED
